//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:11


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *OCTREESCENE_LIBEXTERNS[] = {
	(void *)&COctreeSceneManagerRO,
	(void *)&COctreeSceneRO,
	(void *)&COctreeSceneManagerRO,
	(void *)&COctreeSceneNodeRO,
	(void *)&SetActiveScene_COctreeSceneManagerRM,
	(void *)&VisitScene_COctreeSceneManagerRM,
	(void *)&VisitSceneFrustum_COctreeSceneManagerRM,
	(void *)&VisitSceneAABB_COctreeSceneManagerRM,
	(void *)&VisitSceneSphere_COctreeSceneManagerRM,
	(void *)&AddSceneObject_COctreeSceneManagerRM,
	(void *)&UpdateBoundingBox_COctreeSceneManagerRM,
	(void *)&RemoveSceneObject_COctreeSceneManagerRM,
	(void *)&RemoveBoundingBoxedObject_COctreeSceneManagerRM,
	(void *)&ClearScene_COctreeSceneManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

