//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:11

#ifndef INCLUDE_SYMBOLS_OCTREESCENE
#define INCLUDE_SYMBOLS_OCTREESCENE
#endif	//#ifndef INCLUDE_SYMBOLS_OCTREESCENE
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *OCTREESCENE_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent COctreeSceneManagerRO;
//Component externs
extern "C" CRegisterComponent COctreeSceneRO;
extern "C" CRegisterComponent COctreeSceneManagerRO;
extern "C" CRegisterComponent COctreeSceneNodeRO;
//Message externs
extern "C" CRegisterMessage SetActiveScene_COctreeSceneManagerRM;
extern "C" CRegisterMessage VisitScene_COctreeSceneManagerRM;
extern "C" CRegisterMessage VisitSceneFrustum_COctreeSceneManagerRM;
extern "C" CRegisterMessage VisitSceneAABB_COctreeSceneManagerRM;
extern "C" CRegisterMessage VisitSceneSphere_COctreeSceneManagerRM;
extern "C" CRegisterMessage AddSceneObject_COctreeSceneManagerRM;
extern "C" CRegisterMessage UpdateBoundingBox_COctreeSceneManagerRM;
extern "C" CRegisterMessage RemoveSceneObject_COctreeSceneManagerRM;
extern "C" CRegisterMessage RemoveBoundingBoxedObject_COctreeSceneManagerRM;
extern "C" CRegisterMessage ClearScene_COctreeSceneManagerRM;

#endif	//#ifdef _LIB
