//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:17

#ifndef INCLUDE_SYMBOLS_SHAPE
#define INCLUDE_SYMBOLS_SHAPE
#endif	//#ifndef INCLUDE_SYMBOLS_SHAPE
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SHAPE_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CShapeManagerRO;
//Component externs
extern "C" CRegisterComponent CAxisAlignedBoxRenderObjectRO;
extern "C" CRegisterComponent CLineRenderObjectRO;
extern "C" CRegisterComponent CObjectOrientedBoxRenderObjectRO;
extern "C" CRegisterComponent CPointRenderObjectRO;
extern "C" CRegisterComponent CShapeManagerRO;
extern "C" CRegisterComponent CSphereRenderObjectRO;
//Message externs
extern "C" CRegisterMessage AddAxisAlignedBox_CShapeManagerRM;
extern "C" CRegisterMessage RemoveAxisAlignedBox_CShapeManagerRM;
extern "C" CRegisterMessage AddObjectOrientedBox_CShapeManagerRM;
extern "C" CRegisterMessage RemoveObjectOrientedBox_CShapeManagerRM;
extern "C" CRegisterMessage AddSphere_CShapeManagerRM;
extern "C" CRegisterMessage RemoveSphere_CShapeManagerRM;
extern "C" CRegisterMessage AddLine_CShapeManagerRM;
extern "C" CRegisterMessage RemoveLine_CShapeManagerRM;

#endif	//#ifdef _LIB
