//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:17


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SHAPE_LIBEXTERNS[] = {
	(void *)&CShapeManagerRO,
	(void *)&CAxisAlignedBoxRenderObjectRO,
	(void *)&CLineRenderObjectRO,
	(void *)&CObjectOrientedBoxRenderObjectRO,
	(void *)&CPointRenderObjectRO,
	(void *)&CShapeManagerRO,
	(void *)&CSphereRenderObjectRO,
	(void *)&AddAxisAlignedBox_CShapeManagerRM,
	(void *)&RemoveAxisAlignedBox_CShapeManagerRM,
	(void *)&AddObjectOrientedBox_CShapeManagerRM,
	(void *)&RemoveObjectOrientedBox_CShapeManagerRM,
	(void *)&AddSphere_CShapeManagerRM,
	(void *)&RemoveSphere_CShapeManagerRM,
	(void *)&AddLine_CShapeManagerRM,
	(void *)&RemoveLine_CShapeManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

