//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:00


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DX9RENDERER_LIBEXTERNS[] = {
	(void *)&CMoviePlayerRO,
	(void *)&CDX9RendererRO,
	(void *)&CHModelManagerRO,
	(void *)&CDX9CubeTextureObjectRO,
	(void *)&CMoviePlayerRO,
	(void *)&CPixelShaderRO,
	(void *)&CDX9RendererRO,
	(void *)&CDX9TextureObjectRO,
	(void *)&CVertexShaderRO,
	(void *)&CHModelManagerRO,
	(void *)&PlayMovie_CMoviePlayerRM,
	(void *)&StopMovie_CMoviePlayerRM,
	(void *)&PauseMovie_CMoviePlayerRM,
	(void *)&SetMovieVolume_CMoviePlayerRM,
	(void *)&IsMovieDone_CMoviePlayerRM,
	(void *)&DestroyRenderer_CMoviePlayerRM,
	(void *)&GetRendererInterface_CDX9RendererRM,
	(void *)&SetDirectories_CDX9RendererRM,
	(void *)&GetRayFromMouseCoords_CDX9RendererRM,
	(void *)&TransformWorldToScreen_CDX9RendererRM,
	(void *)0
};

#endif	//#ifdef _LIB

