//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:44

#ifndef INCLUDE_SYMBOLS_LOADSAVEMANAGER
#define INCLUDE_SYMBOLS_LOADSAVEMANAGER
#endif	//#ifndef INCLUDE_SYMBOLS_LOADSAVEMANAGER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LOADSAVEMANAGER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CLoadSaveManagerRO;
//Component externs
extern "C" CRegisterComponent CLoadSaveManagerRO;
//Message externs
extern "C" CRegisterMessage LoadFileByExtension_CLoadSaveManagerRM;
extern "C" CRegisterMessage SaveFileByExtension_CLoadSaveManagerRM;
extern "C" CRegisterMessage UnloadFileByExtension_CLoadSaveManagerRM;
extern "C" CRegisterMessage RegisterLoadSaveComponent_CLoadSaveManagerRM;
extern "C" CRegisterMessage GetFilterStrings_CLoadSaveManagerRM;
extern "C" CRegisterMessage GetFileVersion_CLoadSaveManagerRM;
extern "C" CRegisterMessage SetFileVersion_CLoadSaveManagerRM;

#endif	//#ifdef _LIB
