//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:58:03


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *GDALIO_LIBEXTERNS[] = {
	(void *)&CGDALIORO,
	(void *)&CGDALIORO,
	(void *)&LoadFile_CGDALIORM,
	(void *)&SaveFile_CGDALIORM,
	(void *)0
};

#endif	//#ifdef _LIB

