//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:58:03

#ifndef INCLUDE_SYMBOLS_GDALIO
#define INCLUDE_SYMBOLS_GDALIO
#endif	//#ifndef INCLUDE_SYMBOLS_GDALIO
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *GDALIO_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CGDALIORO;
//Component externs
extern "C" CRegisterComponent CGDALIORO;
//Message externs
extern "C" CRegisterMessage LoadFile_CGDALIORM;
extern "C" CRegisterMessage SaveFile_CGDALIORM;

#endif	//#ifdef _LIB
