//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:43


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *GAMEUTILITIES_LIBEXTERNS[] = {
	(void *)&CFadeUtilityRO,
	(void *)&CFadeUtilityRO,
	(void *)&CTurretRO,
	(void *)&ProcessFade_CFadeUtilityRM,
	(void *)&GlobalUpdateTick_CFadeUtilityRM,
	(void *)&SetTarget_CTurretRM,
	(void *)0
};

#endif	//#ifdef _LIB

