//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:43

#ifndef INCLUDE_SYMBOLS_GAMEUTILITIES
#define INCLUDE_SYMBOLS_GAMEUTILITIES
#endif	//#ifndef INCLUDE_SYMBOLS_GAMEUTILITIES
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *GAMEUTILITIES_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CFadeUtilityRO;
//Component externs
extern "C" CRegisterComponent CFadeUtilityRO;
extern "C" CRegisterComponent CTurretRO;
//Message externs
extern "C" CRegisterMessage ProcessFade_CFadeUtilityRM;
extern "C" CRegisterMessage GlobalUpdateTick_CFadeUtilityRM;
extern "C" CRegisterMessage SetTarget_CTurretRM;

#endif	//#ifdef _LIB
