//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14

#ifndef INCLUDE_SYMBOLS_LANGUAGELOADER
#define INCLUDE_SYMBOLS_LANGUAGELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_LANGUAGELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LANGUAGELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CLanguageLoaderRO;
//Component externs
extern "C" CRegisterComponent CLanguageLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CLanguageLoaderRM;
extern "C" CRegisterMessage SaveFile_CLanguageLoaderRM;

#endif	//#ifdef _LIB
