//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LANGUAGELOADER_LIBEXTERNS[] = {
	(void *)&CLanguageLoaderRO,
	(void *)&CLanguageLoaderRO,
	(void *)&LoadFile_CLanguageLoaderRM,
	(void *)&SaveFile_CLanguageLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

