//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:07

#ifndef INCLUDE_SYMBOLS_WEATHER
#define INCLUDE_SYMBOLS_WEATHER
#endif	//#ifndef INCLUDE_SYMBOLS_WEATHER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *WEATHER_LIBEXTERNS[];
//Singleton externs
//Component externs
extern "C" CRegisterComponent CWeatherRenderObjectRO;
//Message externs

#endif	//#ifdef _LIB
