//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:07


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *WEATHER_LIBEXTERNS[] = {
	(void *)&CWeatherRenderObjectRO,
	(void *)0
};

#endif	//#ifdef _LIB

