//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:24

#ifndef INCLUDE_SYMBOLS_HIERARCHICALMODEL
#define INCLUDE_SYMBOLS_HIERARCHICALMODEL
#endif	//#ifndef INCLUDE_SYMBOLS_HIERARCHICALMODEL
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *HIERARCHICALMODEL_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CHModelManagerRO;
//Component externs
extern "C" CRegisterComponent CHModelManagerRO;
extern "C" CRegisterComponent HierarchicalAnimationRO;
extern "C" CRegisterComponent CHierarchicalModelRO;
extern "C" CRegisterComponent HierarchicalModelTypeRO;
//Message externs
extern "C" CRegisterMessage GetHierarchyTemplate_HierarchicalAnimationRM;
extern "C" CRegisterMessage GetAnimationTime_HierarchicalAnimationRM;
extern "C" CRegisterMessage GetGlobalBoneInfo_CHierarchicalModelRM;
extern "C" CRegisterMessage SetGlobalBoneInfo_CHierarchicalModelRM;
extern "C" CRegisterMessage GetOffsetBoneInfo_CHierarchicalModelRM;
extern "C" CRegisterMessage SetOffsetBoneInfo_CHierarchicalModelRM;
extern "C" CRegisterMessage PlayMatrixAnimation_CHierarchicalModelRM;
extern "C" CRegisterMessage GetBoundingSphere_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGeometryAllocations_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGeometryAllocationByName_CHierarchicalModelRM;
extern "C" CRegisterMessage GetBoundingBox_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGlobalPosition_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGlobalEuler_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGlobalScale_CHierarchicalModelRM;
extern "C" CRegisterMessage GetGlobalTransform_CHierarchicalModelRM;
extern "C" CRegisterMessage SetSkeletonPose_CHierarchicalModelRM;
extern "C" CRegisterMessage EnablePhysicsAnimations_CHierarchicalModelRM;
extern "C" CRegisterMessage GetParentName_CHierarchicalModelRM;
extern "C" CRegisterMessage SetMaterialOverride_CHierarchicalModelRM;
extern "C" CRegisterMessage ClearMaterialOverride_CHierarchicalModelRM;
extern "C" CRegisterMessage AttachSceneObject_CHierarchicalModelRM;
extern "C" CRegisterMessage AlignToSceneObject_CHierarchicalModelRM;
extern "C" CRegisterMessage GetHierarchyTemplate_HierarchicalModelTypeRM;
extern "C" CRegisterMessage GetChildID_HierarchicalModelTypeRM;

#endif	//#ifdef _LIB
