//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:24


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *HIERARCHICALMODEL_LIBEXTERNS[] = {
	(void *)&CHModelManagerRO,
	(void *)&CHModelManagerRO,
	(void *)&HierarchicalAnimationRO,
	(void *)&CHierarchicalModelRO,
	(void *)&HierarchicalModelTypeRO,
	(void *)&GetHierarchyTemplate_HierarchicalAnimationRM,
	(void *)&GetAnimationTime_HierarchicalAnimationRM,
	(void *)&GetGlobalBoneInfo_CHierarchicalModelRM,
	(void *)&SetGlobalBoneInfo_CHierarchicalModelRM,
	(void *)&GetOffsetBoneInfo_CHierarchicalModelRM,
	(void *)&SetOffsetBoneInfo_CHierarchicalModelRM,
	(void *)&PlayMatrixAnimation_CHierarchicalModelRM,
	(void *)&GetBoundingSphere_CHierarchicalModelRM,
	(void *)&GetGeometryAllocations_CHierarchicalModelRM,
	(void *)&GetGeometryAllocationByName_CHierarchicalModelRM,
	(void *)&GetBoundingBox_CHierarchicalModelRM,
	(void *)&GetGlobalPosition_CHierarchicalModelRM,
	(void *)&GetGlobalEuler_CHierarchicalModelRM,
	(void *)&GetGlobalScale_CHierarchicalModelRM,
	(void *)&GetGlobalTransform_CHierarchicalModelRM,
	(void *)&SetSkeletonPose_CHierarchicalModelRM,
	(void *)&EnablePhysicsAnimations_CHierarchicalModelRM,
	(void *)&GetParentName_CHierarchicalModelRM,
	(void *)&SetMaterialOverride_CHierarchicalModelRM,
	(void *)&ClearMaterialOverride_CHierarchicalModelRM,
	(void *)&AttachSceneObject_CHierarchicalModelRM,
	(void *)&AlignToSceneObject_CHierarchicalModelRM,
	(void *)&GetHierarchyTemplate_HierarchicalModelTypeRM,
	(void *)&GetChildID_HierarchicalModelTypeRM,
	(void *)0
};

#endif	//#ifdef _LIB

