//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:12


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *GUILOADER_LIBEXTERNS[] = {
	(void *)&CXMLGuiLoaderRO,
	(void *)&CXMLGuiLoaderRO,
	(void *)&LoadFile_CXMLGuiLoaderRM,
	(void *)&SaveFile_CXMLGuiLoaderRM,
	(void *)&GetGUIVersion_CXMLGuiLoaderRM,
	(void *)&SetGUIVersion_CXMLGuiLoaderRM,
	(void *)&GetFileResolution_CXMLGuiLoaderRM,
	(void *)&GetPageList_CXMLGuiLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

