//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:12

#ifndef INCLUDE_SYMBOLS_GUILOADER
#define INCLUDE_SYMBOLS_GUILOADER
#endif	//#ifndef INCLUDE_SYMBOLS_GUILOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *GUILOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CXMLGuiLoaderRO;
//Component externs
extern "C" CRegisterComponent CXMLGuiLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CXMLGuiLoaderRM;
extern "C" CRegisterMessage SaveFile_CXMLGuiLoaderRM;
extern "C" CRegisterMessage GetGUIVersion_CXMLGuiLoaderRM;
extern "C" CRegisterMessage SetGUIVersion_CXMLGuiLoaderRM;
extern "C" CRegisterMessage GetFileResolution_CXMLGuiLoaderRM;
extern "C" CRegisterMessage GetPageList_CXMLGuiLoaderRM;

#endif	//#ifdef _LIB
