//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:08


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *VARIABLELIST_LIBEXTERNS[] = {
	(void *)&CVariableListRO,
	(void *)0
};

#endif	//#ifdef _LIB

