//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:08

#ifndef INCLUDE_SYMBOLS_VARIABLELIST
#define INCLUDE_SYMBOLS_VARIABLELIST
#endif	//#ifndef INCLUDE_SYMBOLS_VARIABLELIST
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *VARIABLELIST_LIBEXTERNS[];
//Singleton externs
//Component externs
extern "C" CRegisterComponent CVariableListRO;
//Message externs

#endif	//#ifdef _LIB
