//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:22

#ifndef INCLUDE_SYMBOLS_LIGHTMAPOBJECT
#define INCLUDE_SYMBOLS_LIGHTMAPOBJECT
#endif	//#ifndef INCLUDE_SYMBOLS_LIGHTMAPOBJECT
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LIGHTMAPOBJECT_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent LightMapManagerRO;
//Component externs
extern "C" CRegisterComponent LightMapGeneratorRO;
extern "C" CRegisterComponent LightMapObjectRO;
extern "C" CRegisterComponent LightMapManagerRO;
extern "C" CRegisterComponent MeshParameterizationRO;
//Message externs
extern "C" CRegisterMessage AddMesh_LightMapGeneratorRM;
extern "C" CRegisterMessage AddLight_LightMapGeneratorRM;
extern "C" CRegisterMessage CalculateLightmaps_LightMapGeneratorRM;
extern "C" CRegisterMessage AddLightmappableObject_LightMapObjectRM;
extern "C" CRegisterMessage GenerateLightmaps_LightMapObjectRM;
extern "C" CRegisterMessage SetLightmapOutputDirectory_LightMapObjectRM;
extern "C" CRegisterMessage BuildLightmapScene_LightMapManagerRM;
extern "C" CRegisterMessage RegisterLightmapCache_LightMapManagerRM;
extern "C" CRegisterMessage UnRegisterLightmapCache_LightMapManagerRM;
extern "C" CRegisterMessage GetLightmapCache_LightMapManagerRM;
extern "C" CRegisterMessage AddLightmappableObject_LightMapManagerRM;
extern "C" CRegisterMessage CreateMeshParameterization_LightMapManagerRM;
extern "C" CRegisterMessage SetGeneratorParams_LightMapManagerRM;
extern "C" CRegisterMessage GetGeneratorParams_LightMapManagerRM;
extern "C" CRegisterMessage SetLightmapOutputDirectory_LightMapManagerRM;
extern "C" CRegisterMessage ResizeLightmapCache_LightMapManagerRM;
extern "C" CRegisterMessage GenerateAtlas_MeshParameterizationRM;
extern "C" CRegisterMessage AddIndexSoup_MeshParameterizationRM;
extern "C" CRegisterMessage AddVertexIndexSoup_MeshParameterizationRM;
extern "C" CRegisterMessage SetMeshTransform_MeshParameterizationRM;
extern "C" CRegisterMessage SetTextureSize_MeshParameterizationRM;
extern "C" CRegisterMessage GetTextureSize_MeshParameterizationRM;
extern "C" CRegisterMessage GetCache_MeshParameterizationRM;
extern "C" CRegisterMessage SetCache_MeshParameterizationRM;
extern "C" CRegisterMessage GetCollapsedMesh_MeshParameterizationRM;
extern "C" CRegisterMessage GetTriangleFaces_MeshParameterizationRM;
extern "C" CRegisterMessage GetMeshTransform_MeshParameterizationRM;
extern "C" CRegisterMessage GetMeshInverseTransform_MeshParameterizationRM;
extern "C" CRegisterMessage GetAABB_MeshParameterizationRM;
extern "C" CRegisterMessage GenerateBounds_MeshParameterizationRM;
extern "C" CRegisterMessage IntersectRayTriangle_MeshParameterizationRM;
extern "C" CRegisterMessage GenerateTriangleTexelData_MeshParameterizationRM;
extern "C" CRegisterMessage GetBaseColorAtTriangleIntersection_MeshParameterizationRM;
extern "C" CRegisterMessage SetNoClone_MeshParameterizationRM;

#endif	//#ifdef _LIB
