//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:22


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LIGHTMAPOBJECT_LIBEXTERNS[] = {
	(void *)&LightMapManagerRO,
	(void *)&LightMapGeneratorRO,
	(void *)&LightMapObjectRO,
	(void *)&LightMapManagerRO,
	(void *)&MeshParameterizationRO,
	(void *)&AddMesh_LightMapGeneratorRM,
	(void *)&AddLight_LightMapGeneratorRM,
	(void *)&CalculateLightmaps_LightMapGeneratorRM,
	(void *)&AddLightmappableObject_LightMapObjectRM,
	(void *)&GenerateLightmaps_LightMapObjectRM,
	(void *)&SetLightmapOutputDirectory_LightMapObjectRM,
	(void *)&BuildLightmapScene_LightMapManagerRM,
	(void *)&RegisterLightmapCache_LightMapManagerRM,
	(void *)&UnRegisterLightmapCache_LightMapManagerRM,
	(void *)&GetLightmapCache_LightMapManagerRM,
	(void *)&AddLightmappableObject_LightMapManagerRM,
	(void *)&CreateMeshParameterization_LightMapManagerRM,
	(void *)&SetGeneratorParams_LightMapManagerRM,
	(void *)&GetGeneratorParams_LightMapManagerRM,
	(void *)&SetLightmapOutputDirectory_LightMapManagerRM,
	(void *)&ResizeLightmapCache_LightMapManagerRM,
	(void *)&GenerateAtlas_MeshParameterizationRM,
	(void *)&AddIndexSoup_MeshParameterizationRM,
	(void *)&AddVertexIndexSoup_MeshParameterizationRM,
	(void *)&SetMeshTransform_MeshParameterizationRM,
	(void *)&SetTextureSize_MeshParameterizationRM,
	(void *)&GetTextureSize_MeshParameterizationRM,
	(void *)&GetCache_MeshParameterizationRM,
	(void *)&SetCache_MeshParameterizationRM,
	(void *)&GetCollapsedMesh_MeshParameterizationRM,
	(void *)&GetTriangleFaces_MeshParameterizationRM,
	(void *)&GetMeshTransform_MeshParameterizationRM,
	(void *)&GetMeshInverseTransform_MeshParameterizationRM,
	(void *)&GetAABB_MeshParameterizationRM,
	(void *)&GenerateBounds_MeshParameterizationRM,
	(void *)&IntersectRayTriangle_MeshParameterizationRM,
	(void *)&GenerateTriangleTexelData_MeshParameterizationRM,
	(void *)&GetBaseColorAtTriangleIntersection_MeshParameterizationRM,
	(void *)&SetNoClone_MeshParameterizationRM,
	(void *)0
};

#endif	//#ifdef _LIB

