//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:48


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *COORDINATETOOL_LIBEXTERNS[] = {
	(void *)&CCoordinateToolManagerRO,
	(void *)&CCoordinateObjectRO,
	(void *)&CCoordinateRenderObjectRO,
	(void *)&CCoordinateToolManagerRO,
	(void *)&GetGlobalPosition_CCoordinateObjectRM,
	(void *)&SetGlobalPosition_CCoordinateObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

