//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *TEXTURELOADER_LIBEXTERNS[] = {
	(void *)&CTextureLoaderRO,
	(void *)&CTextureLoaderRO,
	(void *)&LoadFile_CTextureLoaderRM,
	(void *)&SaveFile_CTextureLoaderRM,
	(void *)&UnloadFile_CTextureLoaderRM,
	(void *)&SetSaveAsFormat_CTextureLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

