//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:15


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *TIMEOFDAY_LIBEXTERNS[] = {
	(void *)&CTimeOfDayObjectRO,
	(void *)&GetTimeOfDayDesc_CTimeOfDayObjectRM,
	(void *)&GetTimeOfDayStart_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDayStart_CTimeOfDayObjectRM,
	(void *)&GetTimeOfDay_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDay_CTimeOfDayObjectRM,
	(void *)&GetTimeOfDayRate_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDayRate_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDayMotion_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDayDoFog_CTimeOfDayObjectRM,
	(void *)&SetTimeOfDayDoLighting_CTimeOfDayObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

