//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:51


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *CAL3DMODEL_LIBEXTERNS[] = {
	(void *)&Cal3DModelManagerRO,
	(void *)&CCal3DCoreAnimationCacheRO,
	(void *)&CCal3DCoreMeshCacheRO,
	(void *)&CCal3DCoreModelCacheRO,
	(void *)&CCal3DCoreSkeletonCacheRO,
	(void *)&Cal3DModelManagerRO,
	(void *)&Cal3DRenderObjectRO,
	(void *)&GetCal3dCallback_Cal3DModelManagerRM,
	(void *)&GetCal3DModelInterface_Cal3DModelManagerRM,
	(void *)&SaveAllCalCubes_Cal3DModelManagerRM,
	(void *)&DestroyRenderer_Cal3DModelManagerRM,
	(void *)&SetCalScaleVariable_Cal3DRenderObjectRM,
	(void *)&GetModelFileId_Cal3DRenderObjectRM,
	(void *)&GetControllerInterface_Cal3DRenderObjectRM,
	(void *)&GetAnimationList_Cal3DRenderObjectRM,
	(void *)&PlayAnimation_Cal3DRenderObjectRM,
	(void *)&PlaySingleCycleAnimation_Cal3DRenderObjectRM,
	(void *)&StopAnimation_Cal3DRenderObjectRM,
	(void *)&StopAllAnimation_Cal3DRenderObjectRM,
	(void *)&StopAllAnimationActions_Cal3DRenderObjectRM,
	(void *)&SetVisibility_Cal3DRenderObjectRM,
	(void *)&SetMatrix_Cal3DRenderObjectRM,
	(void *)&GetBoundingSphere_Cal3DRenderObjectRM,
	(void *)&RegisterAnimationCallback_Cal3DRenderObjectRM,
	(void *)&UnregisterAnimationCallback_Cal3DRenderObjectRM,
	(void *)&UnregisterAllAnimationCallbacks_Cal3DRenderObjectRM,
	(void *)&GetAnimationId_Cal3DRenderObjectRM,
	(void *)&GetGlobalBoneInfo_Cal3DRenderObjectRM,
	(void *)&RemoveFromQuadTree_Cal3DRenderObjectRM,
	(void *)&AddToQuadTree_Cal3DRenderObjectRM,
	(void *)&GetModelFileName_Cal3DRenderObjectRM,
	(void *)&GetGeometryAllocations_Cal3DRenderObjectRM,
	(void *)&GetBoundingBox_Cal3DRenderObjectRM,
	(void *)&SetLightmapData_Cal3DRenderObjectRM,
	(void *)&GetParentName_Cal3DRenderObjectRM,
	(void *)&SetSkeletonPose_Cal3DRenderObjectRM,
	(void *)&GetSkeletonPose_Cal3DRenderObjectRM,
	(void *)&EnablePhysicsAnimations_Cal3DRenderObjectRM,
	(void *)&GetRenderObjectInterface_Cal3DRenderObjectRM,
	(void *)&SetDrawSkeleton_Cal3DRenderObjectRM,
	(void *)&SetMaterialOverride_Cal3DRenderObjectRM,
	(void *)&ClearMaterialOverride_Cal3DRenderObjectRM,
	(void *)&SetRenderOffset_Cal3DRenderObjectRM,
	(void *)&GetRenderOffset_Cal3DRenderObjectRM,
	(void *)&PauseAnimations_Cal3DRenderObjectRM,
	(void *)&AttachSceneObject_Cal3DRenderObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

