//Autogenerated Static Lib File:
//Generated on: 03/23/09 10:37:09

#ifndef INCLUDE_SYMBOLS_HIERARCHICALMODELLOADER
#define INCLUDE_SYMBOLS_HIERARCHICALMODELLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_HIERARCHICALMODELLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *HIERARCHICALMODELLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CHierarchicalAnimationLoaderRO;
extern "C" CRegisterComponent CHierarchicalModelLoaderRO;
//Component externs
extern "C" CRegisterComponent CHierarchicalAnimationLoaderRO;
extern "C" CRegisterComponent CHierarchicalModelLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CHierarchicalAnimationLoaderRM;
extern "C" CRegisterMessage SaveFile_CHierarchicalAnimationLoaderRM;
extern "C" CRegisterMessage LoadFile_CHierarchicalModelLoaderRM;
extern "C" CRegisterMessage SaveFile_CHierarchicalModelLoaderRM;

#endif	//#ifdef _LIB
