//Autogenerated Static Lib File:
//Generated on: 03/23/09 10:37:09


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *HIERARCHICALMODELLOADER_LIBEXTERNS[] = {
	(void *)&CHierarchicalAnimationLoaderRO,
	(void *)&CHierarchicalModelLoaderRO,
	(void *)&CHierarchicalAnimationLoaderRO,
	(void *)&CHierarchicalModelLoaderRO,
	(void *)&LoadFile_CHierarchicalAnimationLoaderRM,
	(void *)&SaveFile_CHierarchicalAnimationLoaderRM,
	(void *)&LoadFile_CHierarchicalModelLoaderRM,
	(void *)&SaveFile_CHierarchicalModelLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

