//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:39


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *OBJECTCUBEMAP_LIBEXTERNS[] = {
	(void *)&CObjectCubeMapManagerRO,
	(void *)&ObjectCubeMapRO,
	(void *)&CObjectCubeMapManagerRO,
	(void *)&SetCubemapData_ObjectCubeMapRM,
	(void *)&GetModelFileName_ObjectCubeMapRM,
	(void *)&LoadObjectCubeMap_CObjectCubeMapManagerRM,
	(void *)&AddVisibleEntitiesToScene_CObjectCubeMapManagerRM,
	(void *)&SetFadeDistance_CObjectCubeMapManagerRM,
	(void *)&GenerateCubeMap_CObjectCubeMapManagerRM,
	(void *)&AddCubeMap_CObjectCubeMapManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

