//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:39

#ifndef INCLUDE_SYMBOLS_OBJECTCUBEMAP
#define INCLUDE_SYMBOLS_OBJECTCUBEMAP
#endif	//#ifndef INCLUDE_SYMBOLS_OBJECTCUBEMAP
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *OBJECTCUBEMAP_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CObjectCubeMapManagerRO;
//Component externs
extern "C" CRegisterComponent ObjectCubeMapRO;
extern "C" CRegisterComponent CObjectCubeMapManagerRO;
//Message externs
extern "C" CRegisterMessage SetCubemapData_ObjectCubeMapRM;
extern "C" CRegisterMessage GetModelFileName_ObjectCubeMapRM;
extern "C" CRegisterMessage LoadObjectCubeMap_CObjectCubeMapManagerRM;
extern "C" CRegisterMessage AddVisibleEntitiesToScene_CObjectCubeMapManagerRM;
extern "C" CRegisterMessage SetFadeDistance_CObjectCubeMapManagerRM;
extern "C" CRegisterMessage GenerateCubeMap_CObjectCubeMapManagerRM;
extern "C" CRegisterMessage AddCubeMap_CObjectCubeMapManagerRM;

#endif	//#ifdef _LIB
