//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:34

#ifndef INCLUDE_SYMBOLS_SKYBOX
#define INCLUDE_SYMBOLS_SKYBOX
#endif	//#ifndef INCLUDE_SYMBOLS_SKYBOX
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SKYBOX_LIBEXTERNS[];
//Singleton externs
//Component externs
extern "C" CRegisterComponent CSkyboxObjectRO;
//Message externs
extern "C" CRegisterMessage SetZOffset_CSkyboxObjectRM;
extern "C" CRegisterMessage GetSkyboxTexture_CSkyboxObjectRM;
extern "C" CRegisterMessage SetSkyboxTexture_CSkyboxObjectRM;

#endif	//#ifdef _LIB
