//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:34


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SKYBOX_LIBEXTERNS[] = {
	(void *)&CSkyboxObjectRO,
	(void *)&SetZOffset_CSkyboxObjectRM,
	(void *)&GetSkyboxTexture_CSkyboxObjectRM,
	(void *)&SetSkyboxTexture_CSkyboxObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

