//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:33


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SPLINE_LIBEXTERNS[] = {
	(void *)&CSplineManagerRO,
	(void *)&CSplineObjectRO,
	(void *)&CSplineManagerRO,
	(void *)&CSplinePointObjectRO,
	(void *)&CSplinePointRenderObjectRO,
	(void *)&CSplineRenderObjectRO,
	(void *)&UpdateSpline_CSplineObjectRM,
	(void *)&GetSplineInfo_CSplineObjectRM,
	(void *)&SetSplineInfo_CSplineObjectRM,
	(void *)&GetSplineRenderPoints_CSplineObjectRM,
	(void *)&GetSplineFirstDerivativePoints_CSplineObjectRM,
	(void *)&GetSplineSecondDerivativePoints_CSplineObjectRM,
	(void *)&EvaluateSpline_CSplineObjectRM,
	(void *)&EvaluateSplineDistance_CSplineObjectRM,
	(void *)&EvaluateSpline1stDerivative_CSplineObjectRM,
	(void *)&EvaluateSpline2ndDerivative_CSplineObjectRM,
	(void *)&EvaluateSplineLookAhead_CSplineObjectRM,
	(void *)&AddPoint_CSplineObjectRM,
	(void *)&AddPointObject_CSplineObjectRM,
	(void *)&InsertPoint_CSplineObjectRM,
	(void *)&InsertPointObject_CSplineObjectRM,
	(void *)&RemovePoint_CSplineObjectRM,
	(void *)&SetMarker_CSplineObjectRM,
	(void *)&GetNearestDistance_CSplineObjectRM,
	(void *)&AdvanceMarker_CSplineObjectRM,
	(void *)&GetMarkerPosition_CSplineObjectRM,
	(void *)&ClearLeadingPoints_CSplineObjectRM,
	(void *)&ClearTrailingPoints_CSplineObjectRM,
	(void *)&ClearPoints_CSplineObjectRM,
	(void *)&SetSplineRenderOn_CSplineObjectRM,
	(void *)&SetSplineRenderOff_CSplineObjectRM,
	(void *)&ShowAllSplines_CSplineManagerRM,
	(void *)&HideAllSplines_CSplineManagerRM,
	(void *)&GetGlobalPosition_CSplinePointObjectRM,
	(void *)&SetGlobalPosition_CSplinePointObjectRM,
	(void *)&SetGlobalPosition_CSplinePointRenderObjectRM,
	(void *)&SetGlobalPosition_CSplineRenderObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

