//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:33

#ifndef INCLUDE_SYMBOLS_SPLINE
#define INCLUDE_SYMBOLS_SPLINE
#endif	//#ifndef INCLUDE_SYMBOLS_SPLINE
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SPLINE_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CSplineManagerRO;
//Component externs
extern "C" CRegisterComponent CSplineObjectRO;
extern "C" CRegisterComponent CSplineManagerRO;
extern "C" CRegisterComponent CSplinePointObjectRO;
extern "C" CRegisterComponent CSplinePointRenderObjectRO;
extern "C" CRegisterComponent CSplineRenderObjectRO;
//Message externs
extern "C" CRegisterMessage UpdateSpline_CSplineObjectRM;
extern "C" CRegisterMessage GetSplineInfo_CSplineObjectRM;
extern "C" CRegisterMessage SetSplineInfo_CSplineObjectRM;
extern "C" CRegisterMessage GetSplineRenderPoints_CSplineObjectRM;
extern "C" CRegisterMessage GetSplineFirstDerivativePoints_CSplineObjectRM;
extern "C" CRegisterMessage GetSplineSecondDerivativePoints_CSplineObjectRM;
extern "C" CRegisterMessage EvaluateSpline_CSplineObjectRM;
extern "C" CRegisterMessage EvaluateSplineDistance_CSplineObjectRM;
extern "C" CRegisterMessage EvaluateSpline1stDerivative_CSplineObjectRM;
extern "C" CRegisterMessage EvaluateSpline2ndDerivative_CSplineObjectRM;
extern "C" CRegisterMessage EvaluateSplineLookAhead_CSplineObjectRM;
extern "C" CRegisterMessage AddPoint_CSplineObjectRM;
extern "C" CRegisterMessage AddPointObject_CSplineObjectRM;
extern "C" CRegisterMessage InsertPoint_CSplineObjectRM;
extern "C" CRegisterMessage InsertPointObject_CSplineObjectRM;
extern "C" CRegisterMessage RemovePoint_CSplineObjectRM;
extern "C" CRegisterMessage SetMarker_CSplineObjectRM;
extern "C" CRegisterMessage GetNearestDistance_CSplineObjectRM;
extern "C" CRegisterMessage AdvanceMarker_CSplineObjectRM;
extern "C" CRegisterMessage GetMarkerPosition_CSplineObjectRM;
extern "C" CRegisterMessage ClearLeadingPoints_CSplineObjectRM;
extern "C" CRegisterMessage ClearTrailingPoints_CSplineObjectRM;
extern "C" CRegisterMessage ClearPoints_CSplineObjectRM;
extern "C" CRegisterMessage SetSplineRenderOn_CSplineObjectRM;
extern "C" CRegisterMessage SetSplineRenderOff_CSplineObjectRM;
extern "C" CRegisterMessage ShowAllSplines_CSplineManagerRM;
extern "C" CRegisterMessage HideAllSplines_CSplineManagerRM;
extern "C" CRegisterMessage GetGlobalPosition_CSplinePointObjectRM;
extern "C" CRegisterMessage SetGlobalPosition_CSplinePointObjectRM;
extern "C" CRegisterMessage SetGlobalPosition_CSplinePointRenderObjectRM;
extern "C" CRegisterMessage SetGlobalPosition_CSplineRenderObjectRM;

#endif	//#ifdef _LIB
