//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:57


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SPLINELOADER_LIBEXTERNS[] = {
	(void *)&CSplineLoaderRO,
	(void *)&CSplineLoaderRO,
	(void *)&LoadFile_CSplineLoaderRM,
	(void *)&SaveFile_CSplineLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

