//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:57

#ifndef INCLUDE_SYMBOLS_SPLINELOADER
#define INCLUDE_SYMBOLS_SPLINELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_SPLINELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SPLINELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CSplineLoaderRO;
//Component externs
extern "C" CRegisterComponent CSplineLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CSplineLoaderRM;
extern "C" CRegisterMessage SaveFile_CSplineLoaderRM;

#endif	//#ifdef _LIB
