//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:58


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SHADEREFFECTLOADER_LIBEXTERNS[] = {
	(void *)&CMaterialLoaderRO,
	(void *)&CMaterialTemplateLoaderRO,
	(void *)&CShaderEffectLoaderRO,
	(void *)&CShaderPathLoaderRO,
	(void *)&CMaterialLoaderRO,
	(void *)&CMaterialTemplateLoaderRO,
	(void *)&CShaderEffectLoaderRO,
	(void *)&CShaderPathLoaderRO,
	(void *)&LoadFile_CMaterialLoaderRM,
	(void *)&SaveFile_CMaterialLoaderRM,
	(void *)&LoadFile_CMaterialTemplateLoaderRM,
	(void *)&SaveFile_CMaterialTemplateLoaderRM,
	(void *)&LoadFile_CShaderEffectLoaderRM,
	(void *)&SaveFile_CShaderEffectLoaderRM,
	(void *)&LoadFile_CShaderPathLoaderRM,
	(void *)&SaveFile_CShaderPathLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

