//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:58

#ifndef INCLUDE_SYMBOLS_SHADEREFFECTLOADER
#define INCLUDE_SYMBOLS_SHADEREFFECTLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_SHADEREFFECTLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SHADEREFFECTLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CMaterialLoaderRO;
extern "C" CRegisterComponent CMaterialTemplateLoaderRO;
extern "C" CRegisterComponent CShaderEffectLoaderRO;
extern "C" CRegisterComponent CShaderPathLoaderRO;
//Component externs
extern "C" CRegisterComponent CMaterialLoaderRO;
extern "C" CRegisterComponent CMaterialTemplateLoaderRO;
extern "C" CRegisterComponent CShaderEffectLoaderRO;
extern "C" CRegisterComponent CShaderPathLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CMaterialLoaderRM;
extern "C" CRegisterMessage SaveFile_CMaterialLoaderRM;
extern "C" CRegisterMessage LoadFile_CMaterialTemplateLoaderRM;
extern "C" CRegisterMessage SaveFile_CMaterialTemplateLoaderRM;
extern "C" CRegisterMessage LoadFile_CShaderEffectLoaderRM;
extern "C" CRegisterMessage SaveFile_CShaderEffectLoaderRM;
extern "C" CRegisterMessage LoadFile_CShaderPathLoaderRM;
extern "C" CRegisterMessage SaveFile_CShaderPathLoaderRM;

#endif	//#ifdef _LIB
