//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:28

#ifndef INCLUDE_SYMBOLS_PHYSICSLOADER
#define INCLUDE_SYMBOLS_PHYSICSLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_PHYSICSLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *PHYSICSLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CPhysicsLoaderRO;
//Component externs
extern "C" CRegisterComponent CPhysicsLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CPhysicsLoaderRM;
extern "C" CRegisterMessage SaveFile_CPhysicsLoaderRM;

#endif	//#ifdef _LIB
