//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:28


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PHYSICSLOADER_LIBEXTERNS[] = {
	(void *)&CPhysicsLoaderRO,
	(void *)&CPhysicsLoaderRO,
	(void *)&LoadFile_CPhysicsLoaderRM,
	(void *)&SaveFile_CPhysicsLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

