//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:50

#ifndef INCLUDE_SYMBOLS_SPAWNLOADER
#define INCLUDE_SYMBOLS_SPAWNLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_SPAWNLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *SPAWNLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CXMLSpawnLoaderRO;
//Component externs
extern "C" CRegisterComponent CXMLSpawnLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage SaveFile_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage CloseFile_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage GetSpawnedName_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage SetSpawnParentName_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage SetSpawnPosition_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage SetSpawnEuler_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage SpawnFromXMLArchive_CXMLSpawnLoaderRM;
extern "C" CRegisterMessage CacheSpawnFile_CXMLSpawnLoaderRM;

#endif	//#ifdef _LIB
