//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:50


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *SPAWNLOADER_LIBEXTERNS[] = {
	(void *)&CXMLSpawnLoaderRO,
	(void *)&CXMLSpawnLoaderRO,
	(void *)&LoadFile_CXMLSpawnLoaderRM,
	(void *)&SaveFile_CXMLSpawnLoaderRM,
	(void *)&CloseFile_CXMLSpawnLoaderRM,
	(void *)&GetSpawnedName_CXMLSpawnLoaderRM,
	(void *)&SetSpawnParentName_CXMLSpawnLoaderRM,
	(void *)&SetSpawnPosition_CXMLSpawnLoaderRM,
	(void *)&SetSpawnEuler_CXMLSpawnLoaderRM,
	(void *)&SpawnFromXMLArchive_CXMLSpawnLoaderRM,
	(void *)&CacheSpawnFile_CXMLSpawnLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

