//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:09


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PROFILER_LIBEXTERNS[] = {
	(void *)&CProfilerManagerRO,
	(void *)&CProfilerManagerRO,
	(void *)&SetProfilerStrobeTime_CProfilerManagerRM,
	(void *)&ShowHideProfilerWindow_CProfilerManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

