//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:33


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *QHSTATEMACHINE_LIBEXTERNS[] = {
	(void *)&CQHStateMachineManagerRO,
	(void *)&CQHStateRO,
	(void *)&CQHStateMachineRO,
	(void *)&CQHStateMachineActionHandlerRO,
	(void *)&CQHStateMachineEventRO,
	(void *)&CQHStateMachineManagerRO,
	(void *)&CQHStateMachineTransitionRO,
	(void *)&CQHStateObjectRO,
	(void *)&GetSchema_CQHStateRM,
	(void *)&SetAbstract_CQHStateRM,
	(void *)&GetAbstract_CQHStateRM,
	(void *)&VisitHierarchy_CQHStateRM,
	(void *)&GetStateMachineStateLabels_CQHStateRM,
	(void *)&GetChildStateNames_CQHStateRM,
	(void *)&GetStateEventLabels_CQHStateRM,
	(void *)&GetStateAvailableEventLabels_CQHStateRM,
	(void *)&ChangeObjectParent_CQHStateRM,
	(void *)&GetEventNameFromLabel_CQHStateRM,
	(void *)&IsLabelEditble_CQHStateRM,
	(void *)&MapToFileName_CQHStateMachineRM,
	(void *)&GetSchema_CQHStateMachineRM,
	(void *)&VisitHierarchy_CQHStateMachineRM,
	(void *)&GetStateMachineStateLabels_CQHStateMachineRM,
	(void *)&GetChildStateNames_CQHStateMachineRM,
	(void *)&GetSchema_CQHStateMachineActionHandlerRM,
	(void *)&SetAbstract_CQHStateMachineActionHandlerRM,
	(void *)&GetAbstract_CQHStateMachineActionHandlerRM,
	(void *)&IsLabelEditble_CQHStateMachineActionHandlerRM,
	(void *)&GetSchema_CQHStateMachineEventRM,
	(void *)&SetAbstract_CQHStateMachineEventRM,
	(void *)&GetAbstract_CQHStateMachineEventRM,
	(void *)&VisitHierarchy_CQHStateMachineEventRM,
	(void *)&GetEventActionHandlers_CQHStateMachineEventRM,
	(void *)&SetEventActionHandlers_CQHStateMachineEventRM,
	(void *)&GetEventTransitions_CQHStateMachineEventRM,
	(void *)&GetStateMachineStateLabels_CQHStateMachineEventRM,
	(void *)&IsLabelEditble_CQHStateMachineEventRM,
	(void *)&Start_CQHStateMachineManagerRM,
	(void *)&Stop_CQHStateMachineManagerRM,
	(void *)&ChangeObjectName_CQHStateMachineManagerRM,
	(void *)&LoadAndInitStateObject_CQHStateMachineManagerRM,
	(void *)&TriggerEventInStateMachine_CQHStateMachineManagerRM,
	(void *)&QueryStateMachineEvents_CQHStateMachineManagerRM,
	(void *)&GetStateMachineName_CQHStateMachineManagerRM,
	(void *)&GetSchema_CQHStateMachineTransitionRM,
	(void *)&SetAbstract_CQHStateMachineTransitionRM,
	(void *)&GetAbstract_CQHStateMachineTransitionRM,
	(void *)&IsLabelEditble_CQHStateMachineTransitionRM,
	(void *)&TriggerEvent_CQHStateObjectRM,
	(void *)&TriggerRecursiveEvent_CQHStateObjectRM,
	(void *)&GetCurrentState_CQHStateObjectRM,
	(void *)&QueryStateMachineEvents_CQHStateObjectRM,
	(void *)&ExecuteCommand_CQHStateObjectRM,
	(void *)&GetSchema_CQHStateObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

