//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:33

#ifndef INCLUDE_SYMBOLS_QHSTATEMACHINE
#define INCLUDE_SYMBOLS_QHSTATEMACHINE
#endif	//#ifndef INCLUDE_SYMBOLS_QHSTATEMACHINE
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *QHSTATEMACHINE_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CQHStateMachineManagerRO;
//Component externs
extern "C" CRegisterComponent CQHStateRO;
extern "C" CRegisterComponent CQHStateMachineRO;
extern "C" CRegisterComponent CQHStateMachineActionHandlerRO;
extern "C" CRegisterComponent CQHStateMachineEventRO;
extern "C" CRegisterComponent CQHStateMachineManagerRO;
extern "C" CRegisterComponent CQHStateMachineTransitionRO;
extern "C" CRegisterComponent CQHStateObjectRO;
//Message externs
extern "C" CRegisterMessage GetSchema_CQHStateRM;
extern "C" CRegisterMessage SetAbstract_CQHStateRM;
extern "C" CRegisterMessage GetAbstract_CQHStateRM;
extern "C" CRegisterMessage VisitHierarchy_CQHStateRM;
extern "C" CRegisterMessage GetStateMachineStateLabels_CQHStateRM;
extern "C" CRegisterMessage GetChildStateNames_CQHStateRM;
extern "C" CRegisterMessage GetStateEventLabels_CQHStateRM;
extern "C" CRegisterMessage GetStateAvailableEventLabels_CQHStateRM;
extern "C" CRegisterMessage ChangeObjectParent_CQHStateRM;
extern "C" CRegisterMessage GetEventNameFromLabel_CQHStateRM;
extern "C" CRegisterMessage IsLabelEditble_CQHStateRM;
extern "C" CRegisterMessage MapToFileName_CQHStateMachineRM;
extern "C" CRegisterMessage GetSchema_CQHStateMachineRM;
extern "C" CRegisterMessage VisitHierarchy_CQHStateMachineRM;
extern "C" CRegisterMessage GetStateMachineStateLabels_CQHStateMachineRM;
extern "C" CRegisterMessage GetChildStateNames_CQHStateMachineRM;
extern "C" CRegisterMessage GetSchema_CQHStateMachineActionHandlerRM;
extern "C" CRegisterMessage SetAbstract_CQHStateMachineActionHandlerRM;
extern "C" CRegisterMessage GetAbstract_CQHStateMachineActionHandlerRM;
extern "C" CRegisterMessage IsLabelEditble_CQHStateMachineActionHandlerRM;
extern "C" CRegisterMessage GetSchema_CQHStateMachineEventRM;
extern "C" CRegisterMessage SetAbstract_CQHStateMachineEventRM;
extern "C" CRegisterMessage GetAbstract_CQHStateMachineEventRM;
extern "C" CRegisterMessage VisitHierarchy_CQHStateMachineEventRM;
extern "C" CRegisterMessage GetEventActionHandlers_CQHStateMachineEventRM;
extern "C" CRegisterMessage SetEventActionHandlers_CQHStateMachineEventRM;
extern "C" CRegisterMessage GetEventTransitions_CQHStateMachineEventRM;
extern "C" CRegisterMessage GetStateMachineStateLabels_CQHStateMachineEventRM;
extern "C" CRegisterMessage IsLabelEditble_CQHStateMachineEventRM;
extern "C" CRegisterMessage Start_CQHStateMachineManagerRM;
extern "C" CRegisterMessage Stop_CQHStateMachineManagerRM;
extern "C" CRegisterMessage ChangeObjectName_CQHStateMachineManagerRM;
extern "C" CRegisterMessage LoadAndInitStateObject_CQHStateMachineManagerRM;
extern "C" CRegisterMessage TriggerEventInStateMachine_CQHStateMachineManagerRM;
extern "C" CRegisterMessage QueryStateMachineEvents_CQHStateMachineManagerRM;
extern "C" CRegisterMessage GetStateMachineName_CQHStateMachineManagerRM;
extern "C" CRegisterMessage GetSchema_CQHStateMachineTransitionRM;
extern "C" CRegisterMessage SetAbstract_CQHStateMachineTransitionRM;
extern "C" CRegisterMessage GetAbstract_CQHStateMachineTransitionRM;
extern "C" CRegisterMessage IsLabelEditble_CQHStateMachineTransitionRM;
extern "C" CRegisterMessage TriggerEvent_CQHStateObjectRM;
extern "C" CRegisterMessage TriggerRecursiveEvent_CQHStateObjectRM;
extern "C" CRegisterMessage GetCurrentState_CQHStateObjectRM;
extern "C" CRegisterMessage QueryStateMachineEvents_CQHStateObjectRM;
extern "C" CRegisterMessage ExecuteCommand_CQHStateObjectRM;
extern "C" CRegisterMessage GetSchema_CQHStateObjectRM;

#endif	//#ifdef _LIB
