//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *HEIGHTMAPLOADER_LIBEXTERNS[] = {
	(void *)&CHMPLoaderRO,
	(void *)&CHMPLoaderRO,
	(void *)&LoadFile_CHMPLoaderRM,
	(void *)&SaveFile_CHMPLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

