//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14

#ifndef INCLUDE_SYMBOLS_HEIGHTMAPLOADER
#define INCLUDE_SYMBOLS_HEIGHTMAPLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_HEIGHTMAPLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *HEIGHTMAPLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CHMPLoaderRO;
//Component externs
extern "C" CRegisterComponent CHMPLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CHMPLoaderRM;
extern "C" CRegisterMessage SaveFile_CHMPLoaderRM;

#endif	//#ifdef _LIB
