//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:13


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *AIOBJECT_LIBEXTERNS[] = {
	(void *)&CAIManagerRO,
	(void *)&CAIManagerRO,
	(void *)&CAIObjectRO,
	(void *)&CAIObjectCommandRO,
	(void *)&Start_CAIManagerRM,
	(void *)&Stop_CAIManagerRM,
	(void *)&StartCommandSequence_CAIObjectRM,
	(void *)&CompleteCurrentCommand_CAIObjectRM,
	(void *)&ClearCommandSequence_CAIObjectRM,
	(void *)&GetCommandString_CAIObjectCommandRM,
	(void *)&CompleteCommand_CAIObjectCommandRM,
	(void *)&CancelCommand_CAIObjectCommandRM,
	(void *)&GetSchema_CAIObjectCommandRM,
	(void *)0
};

#endif	//#ifdef _LIB

