//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:58:03


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DATABASEIO_LIBEXTERNS[] = {
	(void *)&CDatabaseIORO,
	(void *)&CDefinedDatabaseLoaderRO,
	(void *)&CSchemaLoaderRO,
	(void *)&CDatabaseIORO,
	(void *)&CDefinedDatabaseLoaderRO,
	(void *)&CSchemaLoaderRO,
	(void *)&LoadFile_CDatabaseIORM,
	(void *)&SaveFile_CDatabaseIORM,
	(void *)&LoadFile_CDefinedDatabaseLoaderRM,
	(void *)&SaveFile_CDefinedDatabaseLoaderRM,
	(void *)&LoadFile_CSchemaLoaderRM,
	(void *)&SaveFile_CSchemaLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

