//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14

#ifndef INCLUDE_SYMBOLS_WORLDLOADER
#define INCLUDE_SYMBOLS_WORLDLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_WORLDLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *WORLDLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CXMLWorldLoaderRO;
//Component externs
extern "C" CRegisterComponent CXMLWorldLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CXMLWorldLoaderRM;
extern "C" CRegisterMessage SaveFile_CXMLWorldLoaderRM;
extern "C" CRegisterMessage GetWorldVersion_CXMLWorldLoaderRM;
extern "C" CRegisterMessage GetLatestVersion_CXMLWorldLoaderRM;

#endif	//#ifdef _LIB
