//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *WORLDLOADER_LIBEXTERNS[] = {
	(void *)&CXMLWorldLoaderRO,
	(void *)&CXMLWorldLoaderRO,
	(void *)&LoadFile_CXMLWorldLoaderRM,
	(void *)&SaveFile_CXMLWorldLoaderRM,
	(void *)&GetWorldVersion_CXMLWorldLoaderRM,
	(void *)&GetLatestVersion_CXMLWorldLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

