//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:34:59

#ifndef INCLUDE_SYMBOLS_FLACKSQUAD
#define INCLUDE_SYMBOLS_FLACKSQUAD
#endif	//#ifndef INCLUDE_SYMBOLS_FLACKSQUAD
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *FLACKSQUAD_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent FlackSquadComponentRO;
extern "C" CRegisterComponent CFlackSquadNetworkRO;
extern "C" CRegisterComponent CGUIFPSDisplayRO;
//Component externs
extern "C" CRegisterComponent FlackSquadComponentRO;
extern "C" CRegisterComponent CFlackSquadNetworkRO;
extern "C" CRegisterComponent CGUIFPSDisplayRO;
extern "C" CRegisterComponent CGUIRadarRO;
//Message externs
extern "C" CRegisterMessage UpArrow_FlackSquadComponentRM;
extern "C" CRegisterMessage DownArrow_FlackSquadComponentRM;
extern "C" CRegisterMessage LeftArrow_FlackSquadComponentRM;
extern "C" CRegisterMessage RightArrow_FlackSquadComponentRM;
extern "C" CRegisterMessage SpaceKeyPress_FlackSquadComponentRM;
extern "C" CRegisterMessage ESCKeyPress_FlackSquadComponentRM;
extern "C" CRegisterMessage KeyPressQ_FlackSquadComponentRM;
extern "C" CRegisterMessage KeyPressE_FlackSquadComponentRM;
extern "C" CRegisterMessage KeyPressF_FlackSquadComponentRM;
extern "C" CRegisterMessage KeyPressR_FlackSquadComponentRM;
extern "C" CRegisterMessage MiddleMousePress_FlackSquadComponentRM;
extern "C" CRegisterMessage MiddleMouseRelease_FlackSquadComponentRM;
extern "C" CRegisterMessage MouseMove_FlackSquadComponentRM;
extern "C" CRegisterMessage LeftMousePress_FlackSquadComponentRM;
extern "C" CRegisterMessage LeftMouseRelease_FlackSquadComponentRM;
extern "C" CRegisterMessage RightMousePress_FlackSquadComponentRM;
extern "C" CRegisterMessage RightMouseRelease_FlackSquadComponentRM;
extern "C" CRegisterMessage Scroll_FlackSquadComponentRM;
extern "C" CRegisterMessage GetPlayerInput_FlackSquadComponentRM;
extern "C" CRegisterMessage Pause_FlackSquadComponentRM;
extern "C" CRegisterMessage cam_move_forward_FlackSquadComponentRM;
extern "C" CRegisterMessage cam_move_backward_FlackSquadComponentRM;
extern "C" CRegisterMessage cam_strafe_left_FlackSquadComponentRM;
extern "C" CRegisterMessage cam_strafe_right_FlackSquadComponentRM;
extern "C" CRegisterMessage EndMission_FlackSquadComponentRM;
extern "C" CRegisterMessage PlaneExplode_FlackSquadComponentRM;
extern "C" CRegisterMessage GotoMenu_FlackSquadComponentRM;
extern "C" CRegisterMessage ProfilerOnOff_FlackSquadComponentRM;
extern "C" CRegisterMessage PhysicsVisualizationOnOff_FlackSquadComponentRM;
extern "C" CRegisterMessage WireframeOnOff_FlackSquadComponentRM;
extern "C" CRegisterMessage NullRendererOnOff_FlackSquadComponentRM;
extern "C" CRegisterMessage EnableContinueMode_FlackSquadComponentRM;
extern "C" CRegisterMessage DisableContinueMode_FlackSquadComponentRM;
extern "C" CRegisterMessage ToggleCameraMode_FlackSquadComponentRM;
extern "C" CRegisterMessage InitGameKeybindings_FlackSquadComponentRM;
extern "C" CRegisterMessage LogMessage_FlackSquadComponentRM;
extern "C" CRegisterMessage EnablePostProcessGlow_FlackSquadComponentRM;
extern "C" CRegisterMessage DisablePostProcessGlow_FlackSquadComponentRM;
extern "C" CRegisterMessage EnableBWPostProcess_FlackSquadComponentRM;
extern "C" CRegisterMessage DisableBWPostProcess_FlackSquadComponentRM;
extern "C" CRegisterMessage DisplayFPS_FlackSquadComponentRM;
extern "C" CRegisterMessage GetPlayerAxisSensitivity_FlackSquadComponentRM;
extern "C" CRegisterMessage SetPlayerAxisSensitivity_FlackSquadComponentRM;
extern "C" CRegisterMessage RadialDirectionX_FlackSquadComponentRM;
extern "C" CRegisterMessage RadialDirectionY_FlackSquadComponentRM;
extern "C" CRegisterMessage RotationalDirectionX_FlackSquadComponentRM;
extern "C" CRegisterMessage RotationalDirectionY_FlackSquadComponentRM;
extern "C" CRegisterMessage AButton_FlackSquadComponentRM;
extern "C" CRegisterMessage BButton_FlackSquadComponentRM;
extern "C" CRegisterMessage XButton_FlackSquadComponentRM;
extern "C" CRegisterMessage YButton_FlackSquadComponentRM;
extern "C" CRegisterMessage BackButton_FlackSquadComponentRM;
extern "C" CRegisterMessage StartButton_FlackSquadComponentRM;
extern "C" CRegisterMessage LBButton_FlackSquadComponentRM;
extern "C" CRegisterMessage RBButton_FlackSquadComponentRM;
extern "C" CRegisterMessage LeftTrigger_FlackSquadComponentRM;
extern "C" CRegisterMessage RightTrigger_FlackSquadComponentRM;
extern "C" CRegisterMessage LeftAnalogPress_FlackSquadComponentRM;
extern "C" CRegisterMessage DPadUp_FlackSquadComponentRM;
extern "C" CRegisterMessage DPadDown_FlackSquadComponentRM;
extern "C" CRegisterMessage DPadLeft_FlackSquadComponentRM;
extern "C" CRegisterMessage DPadRight_FlackSquadComponentRM;
extern "C" CRegisterMessage SetLeftMotorSpeed_FlackSquadComponentRM;
extern "C" CRegisterMessage SetRightMotorSpeed_FlackSquadComponentRM;
extern "C" CRegisterMessage JoystickConnected_FlackSquadComponentRM;
extern "C" CRegisterMessage JoystickDisconnected_FlackSquadComponentRM;
extern "C" CRegisterMessage ShowMenu_FlackSquadComponentRM;
extern "C" CRegisterMessage HideMenu_FlackSquadComponentRM;
extern "C" CRegisterMessage StartMission_FlackSquadComponentRM;
extern "C" CRegisterMessage RecvNetworkPacket_CFlackSquadNetworkRM;
extern "C" CRegisterMessage NetworkStateChanged_CFlackSquadNetworkRM;
extern "C" CRegisterMessage NetworkGameSearchComplete_CFlackSquadNetworkRM;
extern "C" CRegisterMessage NetworkPlayerLeaving_CFlackSquadNetworkRM;
extern "C" CRegisterMessage NetworkPlayerJoining_CFlackSquadNetworkRM;
extern "C" CRegisterMessage NetworkPlayerReadinessChanged_CFlackSquadNetworkRM;
extern "C" CRegisterMessage XBoxGameInviteAccepted_CFlackSquadNetworkRM;
extern "C" CRegisterMessage GetFrameRate_CGUIFPSDisplayRM;
extern "C" CRegisterMessage SetPosition_CGUIRadarRM;
extern "C" CRegisterMessage SetSize_CGUIRadarRM;
extern "C" CRegisterMessage GetPosition_CGUIRadarRM;
extern "C" CRegisterMessage GetSize_CGUIRadarRM;
extern "C" CRegisterMessage SetTurretPosition_CGUIRadarRM;
extern "C" CRegisterMessage SetTurretBearing_CGUIRadarRM;
extern "C" CRegisterMessage SetRadarRadius_CGUIRadarRM;
extern "C" CRegisterMessage CheckNameInRadarRange_CGUIRadarRM;
extern "C" CRegisterMessage GetFrameRate_CGUIRadarRM;

#endif	//#ifdef _LIB
