//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:58


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DATABASE_LIBEXTERNS[] = {
	(void *)&CDatabaseManagerRO,
	(void *)&CDatabaseRO,
	(void *)&CDatabaseEntryRO,
	(void *)&CDatabaseItemRO,
	(void *)&CDatabaseManagerRO,
	(void *)&CDatabaseSchemaRO,
	(void *)&CDefinedDatabaseRO,
	(void *)&CSchemaItemRO,
	(void *)&GetDatabaseBySchema_CDatabaseRM,
	(void *)&GetDBFileName_CDatabaseRM,
	(void *)&GetDBSchemaFileName_CDatabaseRM,
	(void *)&GetAttribute_CDatabaseEntryRM,
	(void *)&GetAttributeType_CDatabaseEntryRM,
	(void *)&SetAttribute_CDatabaseEntryRM,
	(void *)&GetSchema_CDatabaseEntryRM,
	(void *)&AddDatabase_CDatabaseManagerRM,
	(void *)&GetDatabase_CDatabaseManagerRM,
	(void *)&GetTypedDatabase_CDatabaseManagerRM,
	(void *)&SetDatabase_CDatabaseManagerRM,
	(void *)&RemoveDatabase_CDatabaseManagerRM,
	(void *)&FindDatabaseByFileName_CDatabaseManagerRM,
	(void *)&CreateGlobalDatabase_CDatabaseManagerRM,
	(void *)&LoadGlobalAttributes_CDatabaseManagerRM,
	(void *)&GetGlobalAttribute_CDatabaseManagerRM,
	(void *)&GetGlobalAttributeType_CDatabaseManagerRM,
	(void *)&SetGlobalAttribute_CDatabaseManagerRM,
	(void *)&MapToFileName_CDatabaseSchemaRM,
	(void *)&GetSchema_CDatabaseSchemaRM,
	(void *)&MapToFileName_CDefinedDatabaseRM,
	(void *)&GetAttribute_CDefinedDatabaseRM,
	(void *)&GetAttributeType_CDefinedDatabaseRM,
	(void *)&GetDatabaseInfo_CDefinedDatabaseRM,
	(void *)&SetAttribute_CDefinedDatabaseRM,
	(void *)&GetIndex_CDefinedDatabaseRM,
	(void *)0
};

#endif	//#ifdef _LIB

