//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:26:21

#ifndef INCLUDE_SYMBOLS_NOVODEXPHYSICS
#define INCLUDE_SYMBOLS_NOVODEXPHYSICS
#endif	//#ifndef INCLUDE_SYMBOLS_NOVODEXPHYSICS
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *NOVODEXPHYSICS_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CPhysicsManagerRO;
//Component externs
extern "C" CRegisterComponent CBoundaryPhysicsObjectRO;
extern "C" CRegisterComponent CCoordinateToolPhysicsObjectRO;
extern "C" CRegisterComponent CEECharacterPhysicsObjectRO;
extern "C" CRegisterComponent CHeightfieldPhysicsObjectRO;
extern "C" CRegisterComponent CPhysicsManagerRO;
extern "C" CRegisterComponent CPhysicsObjectRO;
extern "C" CRegisterComponent CPickingPhysicsObjectRO;
extern "C" CRegisterComponent CTriggerPhysicsObjectRO;
//Message externs
extern "C" CRegisterMessage MoveCharacter_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetCharacterPosition_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetCharacterHeight_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetCharacterWidth_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetMaxVelocity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetActorCollisionGroup_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetLinearVelocity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetAngularVelocity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage GetLinearVelocity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage GetAngularVelocity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetLinearMomentum_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetAngularMomentum_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage GetLinearMomentum_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage GetAngularMomentum_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetKinematic_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetDynamic_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage EnableGravity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage DisableGravity_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage LockHorizontalAxies_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage UnLockHorizontalAxies_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage GetLocalPosition_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage SetLocalPosition_CEECharacterPhysicsObjectRM;
extern "C" CRegisterMessage Start_CPhysicsManagerRM;
extern "C" CRegisterMessage Stop_CPhysicsManagerRM;
extern "C" CRegisterMessage SetCollisionPair_CPhysicsManagerRM;
extern "C" CRegisterMessage SetContactPair_CPhysicsManagerRM;
extern "C" CRegisterMessage Raycast_CPhysicsManagerRM;
extern "C" CRegisterMessage RaycastArchive_CPhysicsManagerRM;
extern "C" CRegisterMessage RaycastList_CPhysicsManagerRM;
extern "C" CRegisterMessage IntersectAABB_CPhysicsManagerRM;
extern "C" CRegisterMessage IntersectOOBB_CPhysicsManagerRM;
extern "C" CRegisterMessage AddNovodexImporter_CPhysicsManagerRM;
extern "C" CRegisterMessage ToggleRemoteVisualizer_CPhysicsManagerRM;
extern "C" CRegisterMessage ShutDownPhysics_CPhysicsManagerRM;
extern "C" CRegisterMessage SetGravity_CPhysicsManagerRM;
extern "C" CRegisterMessage SetPhysicsScale_CPhysicsManagerRM;
extern "C" CRegisterMessage SetForceMoveActors_CPhysicsManagerRM;
extern "C" CRegisterMessage ForceKinematic_CPhysicsManagerRM;
extern "C" CRegisterMessage ApplyForce_CPhysicsObjectRM;
extern "C" CRegisterMessage ApplyTorque_CPhysicsObjectRM;
extern "C" CRegisterMessage SetLinearVelocity_CPhysicsObjectRM;
extern "C" CRegisterMessage SetAngularVelocity_CPhysicsObjectRM;
extern "C" CRegisterMessage GetLinearVelocity_CPhysicsObjectRM;
extern "C" CRegisterMessage GetAngularVelocity_CPhysicsObjectRM;
extern "C" CRegisterMessage SetLinearMomentum_CPhysicsObjectRM;
extern "C" CRegisterMessage SetAngularMomentum_CPhysicsObjectRM;
extern "C" CRegisterMessage GetLinearMomentum_CPhysicsObjectRM;
extern "C" CRegisterMessage GetAngularMomentum_CPhysicsObjectRM;
extern "C" CRegisterMessage SetLinearDamping_CPhysicsObjectRM;
extern "C" CRegisterMessage SetAngularDamping_CPhysicsObjectRM;
extern "C" CRegisterMessage EnableVisualization_CPhysicsObjectRM;
extern "C" CRegisterMessage DisableVisualization_CPhysicsObjectRM;
extern "C" CRegisterMessage SetKinematic_CPhysicsObjectRM;
extern "C" CRegisterMessage SetDynamic_CPhysicsObjectRM;
extern "C" CRegisterMessage ReinitPhysics_CPhysicsObjectRM;
extern "C" CRegisterMessage LockTranslationAxis_CPhysicsObjectRM;
extern "C" CRegisterMessage LockRotationAxis_CPhysicsObjectRM;
extern "C" CRegisterMessage EnablePhysicsAnimations_CPhysicsObjectRM;
extern "C" CRegisterMessage SetHierarchalData_CPhysicsObjectRM;
extern "C" CRegisterMessage ForceSetGlobalPosition_CPhysicsObjectRM;
extern "C" CRegisterMessage GetActorPositionByName_CPhysicsObjectRM;
extern "C" CRegisterMessage SetActorVelocityByName_CPhysicsObjectRM;
extern "C" CRegisterMessage GetActorVelocityByName_CPhysicsObjectRM;
extern "C" CRegisterMessage SetActorCollisionGroup_CPhysicsObjectRM;
extern "C" CRegisterMessage BreakAllJoints_CPhysicsObjectRM;
extern "C" CRegisterMessage BreakJoint_CPhysicsObjectRM;
extern "C" CRegisterMessage GetClothPhysicsGeometry_CPhysicsObjectRM;
extern "C" CRegisterMessage EnableGravity_CPhysicsObjectRM;
extern "C" CRegisterMessage DisableGravity_CPhysicsObjectRM;
extern "C" CRegisterMessage EnableTrigger_CPhysicsObjectRM;
extern "C" CRegisterMessage SetCollisionSurrogate_CPhysicsObjectRM;

#endif	//#ifdef _LIB
