//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:04


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DETAILOBJECT_LIBEXTERNS[] = {
	(void *)&CDetailObjectRO,
	(void *)&GetGlobalPosition_CDetailObjectRM,
	(void *)&SetGlobalPosition_CDetailObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

