//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:04

#ifndef INCLUDE_SYMBOLS_DETAILOBJECT
#define INCLUDE_SYMBOLS_DETAILOBJECT
#endif	//#ifndef INCLUDE_SYMBOLS_DETAILOBJECT
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *DETAILOBJECT_LIBEXTERNS[];
//Singleton externs
//Component externs
extern "C" CRegisterComponent CDetailObjectRO;
//Message externs
extern "C" CRegisterMessage GetGlobalPosition_CDetailObjectRM;
extern "C" CRegisterMessage SetGlobalPosition_CDetailObjectRM;

#endif	//#ifdef _LIB
