//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:41


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *NAVMESH_LIBEXTERNS[] = {
	(void *)&CNavMeshManagerRO,
	(void *)&CNavMeshObjectRO,
	(void *)&CNavMeshManagerRO,
	(void *)&CNavMeshRenderObjectRO,
	(void *)&GenerateNavMesh_CNavMeshObjectRM,
	(void *)&VisualizeNavMesh_CNavMeshObjectRM,
	(void *)&Start_CNavMeshManagerRM,
	(void *)&Stop_CNavMeshManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

