//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:48


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *ENTITYQUERY_LIBEXTERNS[] = {
	(void *)&CEntityQueryRO,
	(void *)&CEntityQueryRO,
	(void *)&SubmitQuery_CEntityQueryRM,
	(void *)&SubmitTypeQuery_CEntityQueryRM,
	(void *)0
};

#endif	//#ifdef _LIB

