//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:48

#ifndef INCLUDE_SYMBOLS_ENTITYQUERY
#define INCLUDE_SYMBOLS_ENTITYQUERY
#endif	//#ifndef INCLUDE_SYMBOLS_ENTITYQUERY
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *ENTITYQUERY_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CEntityQueryRO;
//Component externs
extern "C" CRegisterComponent CEntityQueryRO;
//Message externs
extern "C" CRegisterMessage SubmitQuery_CEntityQueryRM;
extern "C" CRegisterMessage SubmitTypeQuery_CEntityQueryRM;

#endif	//#ifdef _LIB
