//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PRECACHELOADER_LIBEXTERNS[] = {
	(void *)&CPrecacheLoaderRO,
	(void *)&CPrecacheLoaderRO,
	(void *)&LoadFile_CPrecacheLoaderRM,
	(void *)&SaveFile_CPrecacheLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

