//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14

#ifndef INCLUDE_SYMBOLS_PRECACHELOADER
#define INCLUDE_SYMBOLS_PRECACHELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_PRECACHELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *PRECACHELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CPrecacheLoaderRO;
//Component externs
extern "C" CRegisterComponent CPrecacheLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CPrecacheLoaderRM;
extern "C" CRegisterMessage SaveFile_CPrecacheLoaderRM;

#endif	//#ifdef _LIB
