//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:48

#ifndef INCLUDE_SYMBOLS_LUANSM
#define INCLUDE_SYMBOLS_LUANSM
#endif	//#ifndef INCLUDE_SYMBOLS_LUANSM
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LUANSM_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CLuaStateHandlerRO;
//Component externs
extern "C" CRegisterComponent CLuaStateHandlerRO;
//Message externs
extern "C" CRegisterMessage RegisterLuaActions_CLuaStateHandlerRM;
extern "C" CRegisterMessage UnregisterLuaActions_CLuaStateHandlerRM;

#endif	//#ifdef _LIB
