//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:48


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LUANSM_LIBEXTERNS[] = {
	(void *)&CLuaStateHandlerRO,
	(void *)&CLuaStateHandlerRO,
	(void *)&RegisterLuaActions_CLuaStateHandlerRM,
	(void *)&UnregisterLuaActions_CLuaStateHandlerRM,
	(void *)0
};

#endif	//#ifdef _LIB

