//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:33

#ifndef INCLUDE_SYMBOLS_PARTICLELOADER
#define INCLUDE_SYMBOLS_PARTICLELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_PARTICLELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *PARTICLELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CParticleEmitterLoaderRO;
extern "C" CRegisterComponent CParticleLoaderRO;
//Component externs
extern "C" CRegisterComponent CParticleEmitterLoaderRO;
extern "C" CRegisterComponent CParticleLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CParticleEmitterLoaderRM;
extern "C" CRegisterMessage SaveFile_CParticleEmitterLoaderRM;
extern "C" CRegisterMessage LoadFile_CParticleLoaderRM;
extern "C" CRegisterMessage LoadBrushFile_CParticleLoaderRM;
extern "C" CRegisterMessage SaveFile_CParticleLoaderRM;
extern "C" CRegisterMessage SaveBrushFile_CParticleLoaderRM;
extern "C" CRegisterMessage NewFile_CParticleLoaderRM;
extern "C" CRegisterMessage NewBrushFile_CParticleLoaderRM;

#endif	//#ifdef _LIB
