//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:33


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PARTICLELOADER_LIBEXTERNS[] = {
	(void *)&CParticleEmitterLoaderRO,
	(void *)&CParticleLoaderRO,
	(void *)&CParticleEmitterLoaderRO,
	(void *)&CParticleLoaderRO,
	(void *)&LoadFile_CParticleEmitterLoaderRM,
	(void *)&SaveFile_CParticleEmitterLoaderRM,
	(void *)&LoadFile_CParticleLoaderRM,
	(void *)&LoadBrushFile_CParticleLoaderRM,
	(void *)&SaveFile_CParticleLoaderRM,
	(void *)&SaveBrushFile_CParticleLoaderRM,
	(void *)&NewFile_CParticleLoaderRM,
	(void *)&NewBrushFile_CParticleLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

