//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:52


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LUALOADER_LIBEXTERNS[] = {
	(void *)&CLuaScriptLoaderRO,
	(void *)&CLuaScriptLoaderRO,
	(void *)&LoadFile_CLuaScriptLoaderRM,
	(void *)&SaveFile_CLuaScriptLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

