//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:47

#ifndef INCLUDE_SYMBOLS_DECALMANAGER
#define INCLUDE_SYMBOLS_DECALMANAGER
#endif	//#ifndef INCLUDE_SYMBOLS_DECALMANAGER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *DECALMANAGER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CDecalManagerRO;
//Component externs
extern "C" CRegisterComponent CDecalManagerRO;
//Message externs
extern "C" CRegisterMessage AddDecalSprite_CDecalManagerRM;
extern "C" CRegisterMessage AddDecalTemp_CDecalManagerRM;

#endif	//#ifdef _LIB
