//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:47


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DECALMANAGER_LIBEXTERNS[] = {
	(void *)&CDecalManagerRO,
	(void *)&CDecalManagerRO,
	(void *)&AddDecalSprite_CDecalManagerRM,
	(void *)&AddDecalTemp_CDecalManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

