//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:46


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PRECACHE_LIBEXTERNS[] = {
	(void *)&CPrecacheManagerRO,
	(void *)&CPrecacheManagerRO,
	(void *)&CPrecacheObjectRO,
	(void *)&Start_CPrecacheManagerRM,
	(void *)&Stop_CPrecacheManagerRM,
	(void *)&LoadFileByExtension_CPrecacheManagerRM,
	(void *)&RegisterLoadSaveComponent_CPrecacheManagerRM,
	(void *)&AddPrecache_CPrecacheManagerRM,
	(void *)&RemovePrecache_CPrecacheManagerRM,
	(void *)&CommitPrecache_CPrecacheManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

