//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:46


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LIGHTMAPCACHELOADER_LIBEXTERNS[] = {
	(void *)&LightmapCacheLoaderRO,
	(void *)&LightmapCacheLoaderRO,
	(void *)&LoadFile_LightmapCacheLoaderRM,
	(void *)&SaveFile_LightmapCacheLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

