//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:46

#ifndef INCLUDE_SYMBOLS_LIGHTMAPCACHELOADER
#define INCLUDE_SYMBOLS_LIGHTMAPCACHELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_LIGHTMAPCACHELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LIGHTMAPCACHELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent LightmapCacheLoaderRO;
//Component externs
extern "C" CRegisterComponent LightmapCacheLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_LightmapCacheLoaderRM;
extern "C" CRegisterMessage SaveFile_LightmapCacheLoaderRM;

#endif	//#ifdef _LIB
