//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:11


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *LANGUAGELOCALIZER_LIBEXTERNS[] = {
	(void *)&CLanguageManagerRO,
	(void *)&CLanguageRO,
	(void *)&CLanguageEntryRO,
	(void *)&CLanguageManagerRO,
	(void *)&LoadLanguage_CLanguageManagerRM,
	(void *)&GetLanguageText_CLanguageManagerRM,
	(void *)&ClearLanguage_CLanguageManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

