//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:11

#ifndef INCLUDE_SYMBOLS_LANGUAGELOCALIZER
#define INCLUDE_SYMBOLS_LANGUAGELOCALIZER
#endif	//#ifndef INCLUDE_SYMBOLS_LANGUAGELOCALIZER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *LANGUAGELOCALIZER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CLanguageManagerRO;
//Component externs
extern "C" CRegisterComponent CLanguageRO;
extern "C" CRegisterComponent CLanguageEntryRO;
extern "C" CRegisterComponent CLanguageManagerRO;
//Message externs
extern "C" CRegisterMessage LoadLanguage_CLanguageManagerRM;
extern "C" CRegisterMessage GetLanguageText_CLanguageManagerRM;
extern "C" CRegisterMessage ClearLanguage_CLanguageManagerRM;

#endif	//#ifdef _LIB
