//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:38


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *STATELOADER_LIBEXTERNS[] = {
	(void *)&CStateLoaderRO,
	(void *)&CStateLoaderRO,
	(void *)&LoadFile_CStateLoaderRM,
	(void *)&SaveFile_CStateLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

