//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:57:38

#ifndef INCLUDE_SYMBOLS_STATELOADER
#define INCLUDE_SYMBOLS_STATELOADER
#endif	//#ifndef INCLUDE_SYMBOLS_STATELOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *STATELOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CStateLoaderRO;
//Component externs
extern "C" CRegisterComponent CStateLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CStateLoaderRM;
extern "C" CRegisterMessage SaveFile_CStateLoaderRM;

#endif	//#ifdef _LIB
