//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:54


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *EELUASCRIPT_LIBEXTERNS[] = {
	(void *)&CLuaManagerRO,
	(void *)&CLuaManagerRO,
	(void *)&CLuaScriptRO,
	(void *)&CLuaScriptVarListRO,
	(void *)&AddScript_CLuaManagerRM,
	(void *)&RemoveScript_CLuaManagerRM,
	(void *)&LoadAndStartScript_CLuaManagerRM,
	(void *)&GetScript_CLuaManagerRM,
	(void *)&ReleaseScript_CLuaManagerRM,
	(void *)&PauseScript_CLuaManagerRM,
	(void *)&RestartScript_CLuaManagerRM,
	(void *)&GetMasterScriptState_CLuaManagerRM,
	(void *)&GetLuaArchive_CLuaManagerRM,
	(void *)&GetScriptStats_CLuaManagerRM,
	(void *)&StartScript_CLuaScriptRM,
	(void *)&SetTableValue_CLuaScriptRM,
	(void *)&SetPropertyTableValue_CLuaScriptRM,
	(void *)&SetGlobalValue_CLuaScriptRM,
	(void *)&GetSchema_CLuaScriptVarListRM,
	(void *)0
};

#endif	//#ifdef _LIB

