//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:54

#ifndef INCLUDE_SYMBOLS_EELUASCRIPT
#define INCLUDE_SYMBOLS_EELUASCRIPT
#endif	//#ifndef INCLUDE_SYMBOLS_EELUASCRIPT
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *EELUASCRIPT_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CLuaManagerRO;
//Component externs
extern "C" CRegisterComponent CLuaManagerRO;
extern "C" CRegisterComponent CLuaScriptRO;
extern "C" CRegisterComponent CLuaScriptVarListRO;
//Message externs
extern "C" CRegisterMessage AddScript_CLuaManagerRM;
extern "C" CRegisterMessage RemoveScript_CLuaManagerRM;
extern "C" CRegisterMessage LoadAndStartScript_CLuaManagerRM;
extern "C" CRegisterMessage GetScript_CLuaManagerRM;
extern "C" CRegisterMessage ReleaseScript_CLuaManagerRM;
extern "C" CRegisterMessage PauseScript_CLuaManagerRM;
extern "C" CRegisterMessage RestartScript_CLuaManagerRM;
extern "C" CRegisterMessage GetMasterScriptState_CLuaManagerRM;
extern "C" CRegisterMessage GetLuaArchive_CLuaManagerRM;
extern "C" CRegisterMessage GetScriptStats_CLuaManagerRM;
extern "C" CRegisterMessage StartScript_CLuaScriptRM;
extern "C" CRegisterMessage SetTableValue_CLuaScriptRM;
extern "C" CRegisterMessage SetPropertyTableValue_CLuaScriptRM;
extern "C" CRegisterMessage SetGlobalValue_CLuaScriptRM;
extern "C" CRegisterMessage GetSchema_CLuaScriptVarListRM;

#endif	//#ifdef _LIB
