//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:59:10


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *ZLIBSTREAMFACTORY_LIBEXTERNS[] = {
	(void *)&CZLibStreamFactoryRO,
	(void *)&CZLibStreamFactoryRO,
	(void *)&CreateStream_File_CZLibStreamFactoryRM,
	(void *)&CheckFileExists_CZLibStreamFactoryRM,
	(void *)&CreateStream_ZipFile_CZLibStreamFactoryRM,
	(void *)&CreateStream_ZipMemory_CZLibStreamFactoryRM,
	(void *)&AddZipFile_CZLibStreamFactoryRM,
	(void *)&EnableZipFileLoading_CZLibStreamFactoryRM,
	(void *)0
};

#endif	//#ifdef _LIB

