//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:59:10

#ifndef INCLUDE_SYMBOLS_ZLIBSTREAMFACTORY
#define INCLUDE_SYMBOLS_ZLIBSTREAMFACTORY
#endif	//#ifndef INCLUDE_SYMBOLS_ZLIBSTREAMFACTORY
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *ZLIBSTREAMFACTORY_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CZLibStreamFactoryRO;
//Component externs
extern "C" CRegisterComponent CZLibStreamFactoryRO;
//Message externs
extern "C" CRegisterMessage CreateStream_File_CZLibStreamFactoryRM;
extern "C" CRegisterMessage CheckFileExists_CZLibStreamFactoryRM;
extern "C" CRegisterMessage CreateStream_ZipFile_CZLibStreamFactoryRM;
extern "C" CRegisterMessage CreateStream_ZipMemory_CZLibStreamFactoryRM;
extern "C" CRegisterMessage AddZipFile_CZLibStreamFactoryRM;
extern "C" CRegisterMessage EnableZipFileLoading_CZLibStreamFactoryRM;

#endif	//#ifdef _LIB
