//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14

#ifndef INCLUDE_SYMBOLS_PROJECTLOADSAVE
#define INCLUDE_SYMBOLS_PROJECTLOADSAVE
#endif	//#ifndef INCLUDE_SYMBOLS_PROJECTLOADSAVE
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *PROJECTLOADSAVE_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CProjectLoadSaveRO;
//Component externs
extern "C" CRegisterComponent CProjectLoadSaveRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CProjectLoadSaveRM;
extern "C" CRegisterMessage SaveFile_CProjectLoadSaveRM;

#endif	//#ifdef _LIB
