//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:14


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *PROJECTLOADSAVE_LIBEXTERNS[] = {
	(void *)&CProjectLoadSaveRO,
	(void *)&CProjectLoadSaveRO,
	(void *)&LoadFile_CProjectLoadSaveRM,
	(void *)&SaveFile_CProjectLoadSaveRM,
	(void *)0
};

#endif	//#ifdef _LIB

