//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:05

#ifndef INCLUDE_SYMBOLS_WATER
#define INCLUDE_SYMBOLS_WATER
#endif	//#ifndef INCLUDE_SYMBOLS_WATER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *WATER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CWaterManagerRO;
//Component externs
extern "C" CRegisterComponent COceanRenderObjectRO;
extern "C" CRegisterComponent CWaterManagerRO;
//Message externs
extern "C" CRegisterMessage SetEnvMapTexture_COceanRenderObjectRM;
extern "C" CRegisterMessage Start_CWaterManagerRM;
extern "C" CRegisterMessage Stop_CWaterManagerRM;

#endif	//#ifdef _LIB
