//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:05


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *WATER_LIBEXTERNS[] = {
	(void *)&CWaterManagerRO,
	(void *)&COceanRenderObjectRO,
	(void *)&CWaterManagerRO,
	(void *)&SetEnvMapTexture_COceanRenderObjectRM,
	(void *)&Start_CWaterManagerRM,
	(void *)&Stop_CWaterManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

