//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:25:32


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *WORLDEVENT_LIBEXTERNS[] = {
	(void *)&CWorldEventManagerRO,
	(void *)&CWorldEventRO,
	(void *)&CWorldEventManagerRO,
	(void *)&CWorldEventTriggerRO,
	(void *)&TriggerWorldEvent_CWorldEventRM,
	(void *)&GetWorldEventInfo_CWorldEventRM,
	(void *)&SetWorldEventEvent_CWorldEventRM,
	(void *)&Start_CWorldEventManagerRM,
	(void *)&Stop_CWorldEventManagerRM,
	(void *)&QueryWorldEventTriggers_CWorldEventManagerRM,
	(void *)&GetWorldEvents_CWorldEventManagerRM,
	(void *)&FindWorldEventTrigger_CWorldEventManagerRM,
	(void *)&BroadcastWorldEvent_CWorldEventManagerRM,
	(void *)&AddWorldEvent_CWorldEventTriggerRM,
	(void *)&RemoveWorldEvent_CWorldEventTriggerRM,
	(void *)&QueryWorldEvents_CWorldEventTriggerRM,
	(void *)&GetWorldEventInfo_CWorldEventTriggerRM,
	(void *)0
};

#endif	//#ifdef _LIB

