//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:57

#ifndef INCLUDE_SYMBOLS_DEFAULTMATH
#define INCLUDE_SYMBOLS_DEFAULTMATH
#endif	//#ifndef INCLUDE_SYMBOLS_DEFAULTMATH
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *DEFAULTMATH_LIBEXTERNS[];
//Singleton externs
//Component externs
//Message externs

#endif	//#ifdef _LIB
