//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:57


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *DEFAULTMATH_LIBEXTERNS[] = {
	(void *)0
};

#endif	//#ifdef _LIB

