//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:27:16

#ifndef INCLUDE_SYMBOLS_TERRAIN
#define INCLUDE_SYMBOLS_TERRAIN
#endif	//#ifndef INCLUDE_SYMBOLS_TERRAIN
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *TERRAIN_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CTerrainManagerRO;
//Component externs
extern "C" CRegisterComponent CTerrainConfigRO;
extern "C" CRegisterComponent CTerrainDecalRenderObjectRO;
extern "C" CRegisterComponent CTerrainManagerRO;
extern "C" CRegisterComponent CTerrainSectorRO;
extern "C" CRegisterComponent CTerrainSectorRenderObjectRO;
extern "C" CRegisterComponent CTerrainWaterRenderObjectRO;
extern "C" CRegisterComponent CHeightmapObjectRO;
//Message externs
extern "C" CRegisterMessage SetPosition_CTerrainDecalRenderObjectRM;
extern "C" CRegisterMessage SetDecalTexture_CTerrainDecalRenderObjectRM;
extern "C" CRegisterMessage SetDecalSize_CTerrainDecalRenderObjectRM;
extern "C" CRegisterMessage SetDecalColor_CTerrainDecalRenderObjectRM;
extern "C" CRegisterMessage TerrainDeform_CTerrainManagerRM;
extern "C" CRegisterMessage GetAffectedTerrainSectors_CTerrainManagerRM;
extern "C" CRegisterMessage SetTerrainConfig_CTerrainManagerRM;
extern "C" CRegisterMessage TerrainManagerCreateTerrain_CTerrainManagerRM;
extern "C" CRegisterMessage TerrainManagerModifyTerrain_CTerrainManagerRM;
extern "C" CRegisterMessage GetTerrainDescriptor_CTerrainManagerRM;
extern "C" CRegisterMessage GetLODDistance_CTerrainManagerRM;
extern "C" CRegisterMessage GetTerrainSectorNeighborInfo_CTerrainManagerRM;
extern "C" CRegisterMessage Start_CTerrainManagerRM;
extern "C" CRegisterMessage Stop_CTerrainManagerRM;
extern "C" CRegisterMessage CreateTerrainDecal_CTerrainManagerRM;
extern "C" CRegisterMessage TerrainSectorDeform_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSectorSetData_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSectorGetData_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSectorGetPosition_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSectorGetBrushAreaInfo_CTerrainSectorRM;
extern "C" CRegisterMessage GetGlobalPosition_CTerrainSectorRM;
extern "C" CRegisterMessage GetGlobalEuler_CTerrainSectorRM;
extern "C" CRegisterMessage GetGlobalScale_CTerrainSectorRM;
extern "C" CRegisterMessage GetGlobalTransform_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSetPath_CTerrainSectorRM;
extern "C" CRegisterMessage GetEntityType_CTerrainSectorRM;
extern "C" CRegisterMessage GetParentName_CTerrainSectorRM;
extern "C" CRegisterMessage IsEntityTypeOf_CTerrainSectorRM;
extern "C" CRegisterMessage TerrainSectorPaint_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainRemoveUnusedLayers_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainLayerInfo_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorSetData_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorInsertLayer_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorSwapLayers_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorRemoveLayer_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorSetState_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorSetBaseTexture_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorGetBaseTexture_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorGetExtents_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage GetTerrainSectorLOD_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorUpdateNeighborLOD_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorUpdateLOD_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorGetPolyData_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorFreePolyData_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorModifyLayerMask_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorLayerGetBrushAreaInfo_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage SetLightmapData_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage GetGeometryAllocations_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage GetLocalMatrixTransform_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSetPath_CTerrainSectorRenderObjectRM;
extern "C" CRegisterMessage TerrainSectorResetVertexData_CTerrainWaterRenderObjectRM;
extern "C" CRegisterMessage SetHeightmapData_CHeightmapObjectRM;
extern "C" CRegisterMessage GetHeightmapData_CHeightmapObjectRM;

#endif	//#ifdef _LIB
