//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:51


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *NODESYSTEM_LIBEXTERNS[] = {
	(void *)&CNodeSystemManagerRO,
	(void *)&CHeightNodeRO,
	(void *)&CHeightNodeRenderObjectRO,
	(void *)&CNodeRO,
	(void *)&CNodeConnectionRO,
	(void *)&CNodeConnectionRenderObjectRO,
	(void *)&CNodeFaceRO,
	(void *)&CNodeFaceRenderObjectRO,
	(void *)&CNodeRenderObjectRO,
	(void *)&CNodeSystemRO,
	(void *)&CNodeSystemManagerRO,
	(void *)&GetGlobalPosition_CHeightNodeRM,
	(void *)&SetGlobalPosition_CHeightNodeRM,
	(void *)&GetSchema_CHeightNodeRM,
	(void *)&GetGlobalPosition_CNodeRM,
	(void *)&SetGlobalPosition_CNodeRM,
	(void *)&GetSchema_CNodeRM,
	(void *)&GetSchema_CNodeConnectionRM,
	(void *)&GetSchema_CNodeFaceRM,
	(void *)&GetGlobalPosition_CNodeSystemRM,
	(void *)&SetGlobalPosition_CNodeSystemRM,
	(void *)&GetSchema_CNodeSystemRM,
	(void *)&GetVertices_CNodeSystemRM,
	(void *)&GetOrderedVertices_CNodeSystemRM,
	(void *)&GetBoundingBox_CNodeSystemRM,
	(void *)&EnableNodeSystemRender_CNodeSystemManagerRM,
	(void *)&DisableNodeSystemRender_CNodeSystemManagerRM,
	(void *)0
};

#endif	//#ifdef _LIB

