//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:51

#ifndef INCLUDE_SYMBOLS_NODESYSTEM
#define INCLUDE_SYMBOLS_NODESYSTEM
#endif	//#ifndef INCLUDE_SYMBOLS_NODESYSTEM
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *NODESYSTEM_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CNodeSystemManagerRO;
//Component externs
extern "C" CRegisterComponent CHeightNodeRO;
extern "C" CRegisterComponent CHeightNodeRenderObjectRO;
extern "C" CRegisterComponent CNodeRO;
extern "C" CRegisterComponent CNodeConnectionRO;
extern "C" CRegisterComponent CNodeConnectionRenderObjectRO;
extern "C" CRegisterComponent CNodeFaceRO;
extern "C" CRegisterComponent CNodeFaceRenderObjectRO;
extern "C" CRegisterComponent CNodeRenderObjectRO;
extern "C" CRegisterComponent CNodeSystemRO;
extern "C" CRegisterComponent CNodeSystemManagerRO;
//Message externs
extern "C" CRegisterMessage GetGlobalPosition_CHeightNodeRM;
extern "C" CRegisterMessage SetGlobalPosition_CHeightNodeRM;
extern "C" CRegisterMessage GetSchema_CHeightNodeRM;
extern "C" CRegisterMessage GetGlobalPosition_CNodeRM;
extern "C" CRegisterMessage SetGlobalPosition_CNodeRM;
extern "C" CRegisterMessage GetSchema_CNodeRM;
extern "C" CRegisterMessage GetSchema_CNodeConnectionRM;
extern "C" CRegisterMessage GetSchema_CNodeFaceRM;
extern "C" CRegisterMessage GetGlobalPosition_CNodeSystemRM;
extern "C" CRegisterMessage SetGlobalPosition_CNodeSystemRM;
extern "C" CRegisterMessage GetSchema_CNodeSystemRM;
extern "C" CRegisterMessage GetVertices_CNodeSystemRM;
extern "C" CRegisterMessage GetOrderedVertices_CNodeSystemRM;
extern "C" CRegisterMessage GetBoundingBox_CNodeSystemRM;
extern "C" CRegisterMessage EnableNodeSystemRender_CNodeSystemManagerRM;
extern "C" CRegisterMessage DisableNodeSystemRender_CNodeSystemManagerRM;

#endif	//#ifdef _LIB
