//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:56

#ifndef INCLUDE_SYMBOLS_CAL3DLOADER
#define INCLUDE_SYMBOLS_CAL3DLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_CAL3DLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *CAL3DLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CCal3dAnimationLoaderRO;
extern "C" CRegisterComponent CCal3dLoaderRO;
extern "C" CRegisterComponent CCal3dMeshLoaderRO;
extern "C" CRegisterComponent CCal3dMeshTextLoaderRO;
extern "C" CRegisterComponent CCal3dSkeletonLoaderRO;
//Component externs
extern "C" CRegisterComponent CCal3dAnimationLoaderRO;
extern "C" CRegisterComponent CCal3dLoaderRO;
extern "C" CRegisterComponent CCal3dMeshLoaderRO;
extern "C" CRegisterComponent CCal3dMeshTextLoaderRO;
extern "C" CRegisterComponent CCal3dSkeletonLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CCal3dAnimationLoaderRM;
extern "C" CRegisterMessage SaveFile_CCal3dAnimationLoaderRM;
extern "C" CRegisterMessage UnloadFile_CCal3dAnimationLoaderRM;
extern "C" CRegisterMessage LoadFile_CCal3dLoaderRM;
extern "C" CRegisterMessage SaveFile_CCal3dLoaderRM;
extern "C" CRegisterMessage UnloadFile_CCal3dLoaderRM;
extern "C" CRegisterMessage LoadFile_CCal3dMeshLoaderRM;
extern "C" CRegisterMessage SaveFile_CCal3dMeshLoaderRM;
extern "C" CRegisterMessage UnloadFile_CCal3dMeshLoaderRM;
extern "C" CRegisterMessage LoadFile_CCal3dMeshTextLoaderRM;
extern "C" CRegisterMessage SaveFile_CCal3dMeshTextLoaderRM;
extern "C" CRegisterMessage LoadFile_CCal3dSkeletonLoaderRM;
extern "C" CRegisterMessage SaveFile_CCal3dSkeletonLoaderRM;
extern "C" CRegisterMessage UnloadFile_CCal3dSkeletonLoaderRM;

#endif	//#ifdef _LIB
