//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:55


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *CAL3DLOADER_LIBEXTERNS[] = {
	(void *)&CCal3dAnimationLoaderRO,
	(void *)&CCal3dLoaderRO,
	(void *)&CCal3dMeshLoaderRO,
	(void *)&CCal3dMeshTextLoaderRO,
	(void *)&CCal3dSkeletonLoaderRO,
	(void *)&CCal3dAnimationLoaderRO,
	(void *)&CCal3dLoaderRO,
	(void *)&CCal3dMeshLoaderRO,
	(void *)&CCal3dMeshTextLoaderRO,
	(void *)&CCal3dSkeletonLoaderRO,
	(void *)&LoadFile_CCal3dAnimationLoaderRM,
	(void *)&SaveFile_CCal3dAnimationLoaderRM,
	(void *)&UnloadFile_CCal3dAnimationLoaderRM,
	(void *)&LoadFile_CCal3dLoaderRM,
	(void *)&SaveFile_CCal3dLoaderRM,
	(void *)&UnloadFile_CCal3dLoaderRM,
	(void *)&LoadFile_CCal3dMeshLoaderRM,
	(void *)&SaveFile_CCal3dMeshLoaderRM,
	(void *)&UnloadFile_CCal3dMeshLoaderRM,
	(void *)&LoadFile_CCal3dMeshTextLoaderRM,
	(void *)&SaveFile_CCal3dMeshTextLoaderRM,
	(void *)&LoadFile_CCal3dSkeletonLoaderRM,
	(void *)&SaveFile_CCal3dSkeletonLoaderRM,
	(void *)&UnloadFile_CCal3dSkeletonLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

