//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:50

#ifndef INCLUDE_SYMBOLS_OBJECTCUBEMAPLOADER
#define INCLUDE_SYMBOLS_OBJECTCUBEMAPLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_OBJECTCUBEMAPLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *OBJECTCUBEMAPLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent ObjectCubeMapLoaderRO;
//Component externs
extern "C" CRegisterComponent ObjectCubeMapLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_ObjectCubeMapLoaderRM;
extern "C" CRegisterMessage SaveFile_ObjectCubeMapLoaderRM;

#endif	//#ifdef _LIB
