//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:50


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *OBJECTCUBEMAPLOADER_LIBEXTERNS[] = {
	(void *)&ObjectCubeMapLoaderRO,
	(void *)&ObjectCubeMapLoaderRO,
	(void *)&LoadFile_ObjectCubeMapLoaderRM,
	(void *)&SaveFile_ObjectCubeMapLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

