//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:48


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *CLOTH_LIBEXTERNS[] = {
	(void *)&CClothManagerRO,
	(void *)&CClothManagerRO,
	(void *)&CClothRenderObjectRO,
	(void *)&Start_CClothManagerRM,
	(void *)&Stop_CClothManagerRM,
	(void *)&GetGeometryAllocations_CClothRenderObjectRM,
	(void *)0
};

#endif	//#ifdef _LIB

