//Autogenerated Static Lib File:
//Generated on: 03/23/09 14:24:48

#ifndef INCLUDE_SYMBOLS_CLOTH
#define INCLUDE_SYMBOLS_CLOTH
#endif	//#ifndef INCLUDE_SYMBOLS_CLOTH
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *CLOTH_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CClothManagerRO;
//Component externs
extern "C" CRegisterComponent CClothManagerRO;
extern "C" CRegisterComponent CClothRenderObjectRO;
//Message externs
extern "C" CRegisterMessage Start_CClothManagerRM;
extern "C" CRegisterMessage Stop_CClothManagerRM;
extern "C" CRegisterMessage GetGeometryAllocations_CClothRenderObjectRM;

#endif	//#ifdef _LIB
