//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:57

#ifndef INCLUDE_SYMBOLS_HLSLSHADERLOADER
#define INCLUDE_SYMBOLS_HLSLSHADERLOADER
#endif	//#ifndef INCLUDE_SYMBOLS_HLSLSHADERLOADER
#ifdef _LIB

namespace ElementalEngine {
struct INITDLLINFO;
class CRegisterComponent;
class CRegisterMessage;
}

using namespace ElementalEngine;


extern void *HLSLSHADERLOADER_LIBEXTERNS[];
//Singleton externs
extern "C" CRegisterComponent CDX9ShaderLoaderRO;
extern "C" CRegisterComponent CDX9ShaderLoaderRO;
//Component externs
extern "C" CRegisterComponent CDX9ShaderLoaderRO;
extern "C" CRegisterComponent CDX9ShaderLoaderRO;
//Message externs
extern "C" CRegisterMessage LoadFile_CDX9ShaderLoaderRM;
extern "C" CRegisterMessage SaveFile_CDX9ShaderLoaderRM;
extern "C" CRegisterMessage LoadFile_CDX9ShaderLoaderRM;
extern "C" CRegisterMessage SaveFile_CDX9ShaderLoaderRM;

#endif	//#ifdef _LIB
