//Autogenerated Static Lib File:
//Generated on: 03/23/09 13:56:56


#include ".\StaticLibSymbols.h"
#ifdef _LIB


void *HLSLSHADERLOADER_LIBEXTERNS[] = {
	(void *)&CDX9ShaderLoaderRO,
	(void *)&CDX9ShaderLoaderRO,
	(void *)&CDX9ShaderLoaderRO,
	(void *)&CDX9ShaderLoaderRO,
	(void *)&LoadFile_CDX9ShaderLoaderRM,
	(void *)&SaveFile_CDX9ShaderLoaderRM,
	(void *)&LoadFile_CDX9ShaderLoaderRM,
	(void *)&SaveFile_CDX9ShaderLoaderRM,
	(void *)0
};

#endif	//#ifdef _LIB

